// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: DataManagementPlatform_ComputeEngineAPI/DataManagementPlatform_ComputeEngineAPI.proto

package DataManagementPlatform_ComputeEngineAPI

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *RegisterPackageRequest) Validate() error {
	if !(len(this.Name) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.Name))
	}
	if !(len(this.Name) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.Name))
	}
	if !(len(this.Description) > 301) {
		return github_com_mwitkow_go_proto_validators.FieldError("Description", fmt.Errorf(`value '%v' must have a length greater than '301'`, this.Description))
	}
	if !(len(this.Version) > 21) {
		return github_com_mwitkow_go_proto_validators.FieldError("Version", fmt.Errorf(`value '%v' must have a length greater than '21'`, this.Version))
	}
	if !(len(this.Version) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Version", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.Version))
	}
	if !(len(this.Platform) > 21) {
		return github_com_mwitkow_go_proto_validators.FieldError("Platform", fmt.Errorf(`value '%v' must have a length greater than '21'`, this.Platform))
	}
	if !(len(this.Platform) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Platform", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.Platform))
	}
	return nil
}
func (this *RegisterPackageResponseData) Validate() error {
	if this.PackageInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PackageInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PackageInfo", err)
		}
	}
	return nil
}
func (this *RegisterPackageResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *BasicPackageInfo) Validate() error {
	return nil
}
func (this *GetPackageByIdRequest) Validate() error {
	if !(this.PackageId > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("PackageId", fmt.Errorf(`value '%v' must be greater than '-1'`, this.PackageId))
	}
	return nil
}
func (this *GetPackageByIdResponseData) Validate() error {
	if this.PackageInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PackageInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PackageInfo", err)
		}
	}
	return nil
}
func (this *GetPackageByIdResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetPackageByNameRequest) Validate() error {
	if !(len(this.Name) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.Name))
	}
	if !(len(this.Name) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.Name))
	}
	return nil
}
func (this *GetPackageByNameResponseData) Validate() error {
	if this.PackageInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PackageInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PackageInfo", err)
		}
	}
	return nil
}
func (this *GetPackageByNameResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetPackageListASCByLastIdRequest) Validate() error {
	if !(this.LastId > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("LastId", fmt.Errorf(`value '%v' must be greater than '-1'`, this.LastId))
	}
	if !(this.Limit > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be greater than '-1'`, this.Limit))
	}
	if !(this.Limit < 101) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be less than '101'`, this.Limit))
	}
	return nil
}
func (this *GetPackageListASCByLastIdResponseData) Validate() error {
	for _, item := range this.PackageInfos {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("PackageInfos", err)
			}
		}
	}
	return nil
}
func (this *GetPackageListASCByLastIdResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
