// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: DataManagementPlatform_ComputeEngineAPI/DataManagementPlatform_ComputeEngineAPI.proto

package DataManagementPlatform_ComputeEngineAPI

import (
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPackageRequest) Reset() {
	*x = RegisterPackageRequest{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPackageRequest) ProtoMessage() {}

func (x *RegisterPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPackageRequest.ProtoReflect.Descriptor instead.
func (*RegisterPackageRequest) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterPackageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterPackageRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterPackageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RegisterPackageResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageInfo   *BasicPackageInfo      `protobuf:"bytes,1,opt,name=package_info,json=packageInfo,proto3" json:"package_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPackageResponseData) Reset() {
	*x = RegisterPackageResponseData{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPackageResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPackageResponseData) ProtoMessage() {}

func (x *RegisterPackageResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPackageResponseData.ProtoReflect.Descriptor instead.
func (*RegisterPackageResponseData) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPackageResponseData) GetPackageInfo() *BasicPackageInfo {
	if x != nil {
		return x.PackageInfo
	}
	return nil
}

type RegisterPackageResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	ErrCode       int32                        `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                       `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *RegisterPackageResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPackageResponse) Reset() {
	*x = RegisterPackageResponse{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPackageResponse) ProtoMessage() {}

func (x *RegisterPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPackageResponse.ProtoReflect.Descriptor instead.
func (*RegisterPackageResponse) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPackageResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *RegisterPackageResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *RegisterPackageResponse) GetData() *RegisterPackageResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type BasicPackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	RegisterTime  int64                  `protobuf:"varint,6,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicPackageInfo) Reset() {
	*x = BasicPackageInfo{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicPackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicPackageInfo) ProtoMessage() {}

func (x *BasicPackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicPackageInfo.ProtoReflect.Descriptor instead.
func (*BasicPackageInfo) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{3}
}

func (x *BasicPackageInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BasicPackageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BasicPackageInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BasicPackageInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *BasicPackageInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BasicPackageInfo) GetRegisterTime() int64 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

type GetPackageByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     int64                  `protobuf:"varint,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageByIdRequest) Reset() {
	*x = GetPackageByIdRequest{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageByIdRequest) ProtoMessage() {}

func (x *GetPackageByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPackageByIdRequest) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{4}
}

func (x *GetPackageByIdRequest) GetPackageId() int64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

type GetPackageByIdResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageInfo   *BasicPackageInfo      `protobuf:"bytes,1,opt,name=package_info,json=packageInfo,proto3" json:"package_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageByIdResponseData) Reset() {
	*x = GetPackageByIdResponseData{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageByIdResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageByIdResponseData) ProtoMessage() {}

func (x *GetPackageByIdResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageByIdResponseData.ProtoReflect.Descriptor instead.
func (*GetPackageByIdResponseData) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{5}
}

func (x *GetPackageByIdResponseData) GetPackageInfo() *BasicPackageInfo {
	if x != nil {
		return x.PackageInfo
	}
	return nil
}

type GetPackageByIdResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ErrCode       int32                       `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                      `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *GetPackageByIdResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageByIdResponse) Reset() {
	*x = GetPackageByIdResponse{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageByIdResponse) ProtoMessage() {}

func (x *GetPackageByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPackageByIdResponse) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{6}
}

func (x *GetPackageByIdResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GetPackageByIdResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetPackageByIdResponse) GetData() *GetPackageByIdResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPackageByOriginIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginId      string                 `protobuf:"bytes,1,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageByOriginIdRequest) Reset() {
	*x = GetPackageByOriginIdRequest{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageByOriginIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageByOriginIdRequest) ProtoMessage() {}

func (x *GetPackageByOriginIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageByOriginIdRequest.ProtoReflect.Descriptor instead.
func (*GetPackageByOriginIdRequest) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{7}
}

func (x *GetPackageByOriginIdRequest) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

type GetPackageByOriginIdResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageInfo   *BasicPackageInfo      `protobuf:"bytes,1,opt,name=package_info,json=packageInfo,proto3" json:"package_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageByOriginIdResponseData) Reset() {
	*x = GetPackageByOriginIdResponseData{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageByOriginIdResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageByOriginIdResponseData) ProtoMessage() {}

func (x *GetPackageByOriginIdResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageByOriginIdResponseData.ProtoReflect.Descriptor instead.
func (*GetPackageByOriginIdResponseData) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{8}
}

func (x *GetPackageByOriginIdResponseData) GetPackageInfo() *BasicPackageInfo {
	if x != nil {
		return x.PackageInfo
	}
	return nil
}

type GetPackageByOriginIdResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	ErrCode       int32                             `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                            `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *GetPackageByOriginIdResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageByOriginIdResponse) Reset() {
	*x = GetPackageByOriginIdResponse{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageByOriginIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageByOriginIdResponse) ProtoMessage() {}

func (x *GetPackageByOriginIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageByOriginIdResponse.ProtoReflect.Descriptor instead.
func (*GetPackageByOriginIdResponse) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{9}
}

func (x *GetPackageByOriginIdResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GetPackageByOriginIdResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetPackageByOriginIdResponse) GetData() *GetPackageByOriginIdResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPackageListASCByLastIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        int64                  `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageListASCByLastIdRequest) Reset() {
	*x = GetPackageListASCByLastIdRequest{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageListASCByLastIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageListASCByLastIdRequest) ProtoMessage() {}

func (x *GetPackageListASCByLastIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageListASCByLastIdRequest.ProtoReflect.Descriptor instead.
func (*GetPackageListASCByLastIdRequest) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{10}
}

func (x *GetPackageListASCByLastIdRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *GetPackageListASCByLastIdRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPackageListASCByLastIdResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageInfos  []*BasicPackageInfo    `protobuf:"bytes,1,rep,name=package_infos,json=packageInfos,proto3" json:"package_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageListASCByLastIdResponseData) Reset() {
	*x = GetPackageListASCByLastIdResponseData{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageListASCByLastIdResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageListASCByLastIdResponseData) ProtoMessage() {}

func (x *GetPackageListASCByLastIdResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageListASCByLastIdResponseData.ProtoReflect.Descriptor instead.
func (*GetPackageListASCByLastIdResponseData) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{11}
}

func (x *GetPackageListASCByLastIdResponseData) GetPackageInfos() []*BasicPackageInfo {
	if x != nil {
		return x.PackageInfos
	}
	return nil
}

type GetPackageListASCByLastIdResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	ErrCode       int32                                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *GetPackageListASCByLastIdResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageListASCByLastIdResponse) Reset() {
	*x = GetPackageListASCByLastIdResponse{}
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageListASCByLastIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageListASCByLastIdResponse) ProtoMessage() {}

func (x *GetPackageListASCByLastIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageListASCByLastIdResponse.ProtoReflect.Descriptor instead.
func (*GetPackageListASCByLastIdResponse) Descriptor() ([]byte, []int) {
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP(), []int{12}
}

func (x *GetPackageListASCByLastIdResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GetPackageListASCByLastIdResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetPackageListASCByLastIdResponse) GetData() *GetPackageListASCByLastIdResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto protoreflect.FileDescriptor

const file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDesc = "" +
	"\n" +
	"UDataManagementPlatform_ComputeEngineAPI/DataManagementPlatform_ComputeEngineAPI.proto\x12'DataManagementPlatform_ComputeEngineAPI\x1a+mwitkow/go-proto-validators/validator.proto\x1a\x1cgoogle/api/annotations.proto\"\xa4\x01\n" +
	"\x16RegisterPackageRequest\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p3x\x00R\x04name\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xe2\xdf\x1f\x03p\xad\x02R\vdescription\x12$\n" +
	"\bplatform\x18\x03 \x01(\tB\b\xe2\xdf\x1f\x04p\x15x\x00R\bplatform\x12\x1b\n" +
	"\x03url\x18\x04 \x01(\tB\t\xe2\xdf\x1f\x05p\xc9\x01x\x00R\x03url\"{\n" +
	"\x1bRegisterPackageResponseData\x12\\\n" +
	"\fpackage_info\x18\x01 \x01(\v29.DataManagementPlatform_ComputeEngineAPI.BasicPackageInfoR\vpackageInfo\"\xa7\x01\n" +
	"\x17RegisterPackageResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12X\n" +
	"\x04data\x18\x03 \x01(\v2D.DataManagementPlatform_ComputeEngineAPI.RegisterPackageResponseDataR\x04data\"\xab\x01\n" +
	"\x10BasicPackageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12#\n" +
	"\rregister_time\x18\x06 \x01(\x03R\fregisterTime\"G\n" +
	"\x15GetPackageByIdRequest\x12.\n" +
	"\n" +
	"package_id\x18\x01 \x01(\x03B\x0f\xe2\xdf\x1f\v\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\tpackageId\"z\n" +
	"\x1aGetPackageByIdResponseData\x12\\\n" +
	"\fpackage_info\x18\x01 \x01(\v29.DataManagementPlatform_ComputeEngineAPI.BasicPackageInfoR\vpackageInfo\"\xa5\x01\n" +
	"\x16GetPackageByIdResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12W\n" +
	"\x04data\x18\x03 \x01(\v2C.DataManagementPlatform_ComputeEngineAPI.GetPackageByIdResponseDataR\x04data\"D\n" +
	"\x1bGetPackageByOriginIdRequest\x12%\n" +
	"\torigin_id\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p3x\x00R\boriginId\"\x80\x01\n" +
	" GetPackageByOriginIdResponseData\x12\\\n" +
	"\fpackage_info\x18\x01 \x01(\v29.DataManagementPlatform_ComputeEngineAPI.BasicPackageInfoR\vpackageInfo\"\xb1\x01\n" +
	"\x1cGetPackageByOriginIdResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12]\n" +
	"\x04data\x18\x03 \x01(\v2I.DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdResponseDataR\x04data\"u\n" +
	" GetPackageListASCByLastIdRequest\x12(\n" +
	"\alast_id\x18\x01 \x01(\x03B\x0f\xe2\xdf\x1f\v\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x06lastId\x12'\n" +
	"\x05limit\x18\x02 \x01(\x05B\x11\xe2\xdf\x1f\r\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x18eR\x05limit\"\x87\x01\n" +
	"%GetPackageListASCByLastIdResponseData\x12^\n" +
	"\rpackage_infos\x18\x01 \x03(\v29.DataManagementPlatform_ComputeEngineAPI.BasicPackageInfoR\fpackageInfos\"\xbb\x01\n" +
	"!GetPackageListASCByLastIdResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12b\n" +
	"\x04data\x18\x03 \x01(\v2N.DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdResponseDataR\x04data2\xe7\x06\n" +
	"\x10ComputeEngineAPI\x12\xc5\x01\n" +
	"\x0fRegisterPackage\x12?.DataManagementPlatform_ComputeEngineAPI.RegisterPackageRequest\x1a@.DataManagementPlatform_ComputeEngineAPI.RegisterPackageResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/computeEngines/packages/register\x12\xc0\x01\n" +
	"\x0eGetPackageById\x12>.DataManagementPlatform_ComputeEngineAPI.GetPackageByIdRequest\x1a?.DataManagementPlatform_ComputeEngineAPI.GetPackageByIdResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v1/computeEngines/packages/queryById\x12\xd8\x01\n" +
	"\x14GetPackageByOriginId\x12D.DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdRequest\x1aE.DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/computeEngines/packages/queryByOriginId\x12\xec\x01\n" +
	"\x19GetPackageListASCByLastId\x12I.DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdRequest\x1aJ.DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdResponse\"8\x82\xd3\xe4\x93\x022\x120/v1/computeEngines/packages/queryListASCByLastIdB,Z*./;DataManagementPlatform_ComputeEngineAPIb\x06proto3"

var (
	file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescOnce sync.Once
	file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescData []byte
)

func file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescGZIP() []byte {
	file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescOnce.Do(func() {
		file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDesc), len(file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDesc)))
	})
	return file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDescData
}

var file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_goTypes = []any{
	(*RegisterPackageRequest)(nil),                // 0: DataManagementPlatform_ComputeEngineAPI.RegisterPackageRequest
	(*RegisterPackageResponseData)(nil),           // 1: DataManagementPlatform_ComputeEngineAPI.RegisterPackageResponseData
	(*RegisterPackageResponse)(nil),               // 2: DataManagementPlatform_ComputeEngineAPI.RegisterPackageResponse
	(*BasicPackageInfo)(nil),                      // 3: DataManagementPlatform_ComputeEngineAPI.BasicPackageInfo
	(*GetPackageByIdRequest)(nil),                 // 4: DataManagementPlatform_ComputeEngineAPI.GetPackageByIdRequest
	(*GetPackageByIdResponseData)(nil),            // 5: DataManagementPlatform_ComputeEngineAPI.GetPackageByIdResponseData
	(*GetPackageByIdResponse)(nil),                // 6: DataManagementPlatform_ComputeEngineAPI.GetPackageByIdResponse
	(*GetPackageByOriginIdRequest)(nil),           // 7: DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdRequest
	(*GetPackageByOriginIdResponseData)(nil),      // 8: DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdResponseData
	(*GetPackageByOriginIdResponse)(nil),          // 9: DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdResponse
	(*GetPackageListASCByLastIdRequest)(nil),      // 10: DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdRequest
	(*GetPackageListASCByLastIdResponseData)(nil), // 11: DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdResponseData
	(*GetPackageListASCByLastIdResponse)(nil),     // 12: DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdResponse
}
var file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_depIdxs = []int32{
	3,  // 0: DataManagementPlatform_ComputeEngineAPI.RegisterPackageResponseData.package_info:type_name -> DataManagementPlatform_ComputeEngineAPI.BasicPackageInfo
	1,  // 1: DataManagementPlatform_ComputeEngineAPI.RegisterPackageResponse.data:type_name -> DataManagementPlatform_ComputeEngineAPI.RegisterPackageResponseData
	3,  // 2: DataManagementPlatform_ComputeEngineAPI.GetPackageByIdResponseData.package_info:type_name -> DataManagementPlatform_ComputeEngineAPI.BasicPackageInfo
	5,  // 3: DataManagementPlatform_ComputeEngineAPI.GetPackageByIdResponse.data:type_name -> DataManagementPlatform_ComputeEngineAPI.GetPackageByIdResponseData
	3,  // 4: DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdResponseData.package_info:type_name -> DataManagementPlatform_ComputeEngineAPI.BasicPackageInfo
	8,  // 5: DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdResponse.data:type_name -> DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdResponseData
	3,  // 6: DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdResponseData.package_infos:type_name -> DataManagementPlatform_ComputeEngineAPI.BasicPackageInfo
	11, // 7: DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdResponse.data:type_name -> DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdResponseData
	0,  // 8: DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI.RegisterPackage:input_type -> DataManagementPlatform_ComputeEngineAPI.RegisterPackageRequest
	4,  // 9: DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI.GetPackageById:input_type -> DataManagementPlatform_ComputeEngineAPI.GetPackageByIdRequest
	7,  // 10: DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI.GetPackageByOriginId:input_type -> DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdRequest
	10, // 11: DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI.GetPackageListASCByLastId:input_type -> DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdRequest
	2,  // 12: DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI.RegisterPackage:output_type -> DataManagementPlatform_ComputeEngineAPI.RegisterPackageResponse
	6,  // 13: DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI.GetPackageById:output_type -> DataManagementPlatform_ComputeEngineAPI.GetPackageByIdResponse
	9,  // 14: DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI.GetPackageByOriginId:output_type -> DataManagementPlatform_ComputeEngineAPI.GetPackageByOriginIdResponse
	12, // 15: DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI.GetPackageListASCByLastId:output_type -> DataManagementPlatform_ComputeEngineAPI.GetPackageListASCByLastIdResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() {
	file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_init()
}
func file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_init() {
	if File_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDesc), len(file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_goTypes,
		DependencyIndexes: file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_depIdxs,
		MessageInfos:      file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_msgTypes,
	}.Build()
	File_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto = out.File
	file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_goTypes = nil
	file_DataManagementPlatform_ComputeEngineAPI_DataManagementPlatform_ComputeEngineAPI_proto_depIdxs = nil
}
