// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: DataManagementPlatform_ComputeEngineAPI/DataManagementPlatform_ComputeEngineAPI.proto

package DataManagementPlatform_ComputeEngineAPI

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComputeEngineAPI_RegisterPackage_FullMethodName           = "/DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI/RegisterPackage"
	ComputeEngineAPI_UploadPackage_FullMethodName             = "/DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI/UploadPackage"
	ComputeEngineAPI_ReloadPackage_FullMethodName             = "/DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI/ReloadPackage"
	ComputeEngineAPI_ReloadAllPackages_FullMethodName         = "/DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI/ReloadAllPackages"
	ComputeEngineAPI_GetPackageById_FullMethodName            = "/DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI/GetPackageById"
	ComputeEngineAPI_GetPackageByOriginId_FullMethodName      = "/DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI/GetPackageByOriginId"
	ComputeEngineAPI_GetPackageListASCByLastId_FullMethodName = "/DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI/GetPackageListASCByLastId"
	ComputeEngineAPI_ComputePackagesCombo_FullMethodName      = "/DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI/ComputePackagesCombo"
)

// ComputeEngineAPIClient is the client API for ComputeEngineAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeEngineAPIClient interface {
	RegisterPackage(ctx context.Context, in *RegisterPackageRequest, opts ...grpc.CallOption) (*RegisterPackageResponse, error)
	UploadPackage(ctx context.Context, in *UploadPackageRequest, opts ...grpc.CallOption) (*UploadPackageResponse, error)
	ReloadPackage(ctx context.Context, in *ReloadPackageRequest, opts ...grpc.CallOption) (*ReloadPackageResponse, error)
	ReloadAllPackages(ctx context.Context, in *ReloadAllPackagesRequest, opts ...grpc.CallOption) (*ReloadAllPackagesResponse, error)
	GetPackageById(ctx context.Context, in *GetPackageByIdRequest, opts ...grpc.CallOption) (*GetPackageByIdResponse, error)
	GetPackageByOriginId(ctx context.Context, in *GetPackageByOriginIdRequest, opts ...grpc.CallOption) (*GetPackageByOriginIdResponse, error)
	GetPackageListASCByLastId(ctx context.Context, in *GetPackageListASCByLastIdRequest, opts ...grpc.CallOption) (*GetPackageListASCByLastIdResponse, error)
	ComputePackagesCombo(ctx context.Context, in *ComputePackageComboRequest, opts ...grpc.CallOption) (*ComputePackageComboResponse, error)
}

type computeEngineAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeEngineAPIClient(cc grpc.ClientConnInterface) ComputeEngineAPIClient {
	return &computeEngineAPIClient{cc}
}

func (c *computeEngineAPIClient) RegisterPackage(ctx context.Context, in *RegisterPackageRequest, opts ...grpc.CallOption) (*RegisterPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPackageResponse)
	err := c.cc.Invoke(ctx, ComputeEngineAPI_RegisterPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeEngineAPIClient) UploadPackage(ctx context.Context, in *UploadPackageRequest, opts ...grpc.CallOption) (*UploadPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPackageResponse)
	err := c.cc.Invoke(ctx, ComputeEngineAPI_UploadPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeEngineAPIClient) ReloadPackage(ctx context.Context, in *ReloadPackageRequest, opts ...grpc.CallOption) (*ReloadPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadPackageResponse)
	err := c.cc.Invoke(ctx, ComputeEngineAPI_ReloadPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeEngineAPIClient) ReloadAllPackages(ctx context.Context, in *ReloadAllPackagesRequest, opts ...grpc.CallOption) (*ReloadAllPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadAllPackagesResponse)
	err := c.cc.Invoke(ctx, ComputeEngineAPI_ReloadAllPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeEngineAPIClient) GetPackageById(ctx context.Context, in *GetPackageByIdRequest, opts ...grpc.CallOption) (*GetPackageByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPackageByIdResponse)
	err := c.cc.Invoke(ctx, ComputeEngineAPI_GetPackageById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeEngineAPIClient) GetPackageByOriginId(ctx context.Context, in *GetPackageByOriginIdRequest, opts ...grpc.CallOption) (*GetPackageByOriginIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPackageByOriginIdResponse)
	err := c.cc.Invoke(ctx, ComputeEngineAPI_GetPackageByOriginId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeEngineAPIClient) GetPackageListASCByLastId(ctx context.Context, in *GetPackageListASCByLastIdRequest, opts ...grpc.CallOption) (*GetPackageListASCByLastIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPackageListASCByLastIdResponse)
	err := c.cc.Invoke(ctx, ComputeEngineAPI_GetPackageListASCByLastId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeEngineAPIClient) ComputePackagesCombo(ctx context.Context, in *ComputePackageComboRequest, opts ...grpc.CallOption) (*ComputePackageComboResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputePackageComboResponse)
	err := c.cc.Invoke(ctx, ComputeEngineAPI_ComputePackagesCombo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeEngineAPIServer is the server API for ComputeEngineAPI service.
// All implementations must embed UnimplementedComputeEngineAPIServer
// for forward compatibility.
type ComputeEngineAPIServer interface {
	RegisterPackage(context.Context, *RegisterPackageRequest) (*RegisterPackageResponse, error)
	UploadPackage(context.Context, *UploadPackageRequest) (*UploadPackageResponse, error)
	ReloadPackage(context.Context, *ReloadPackageRequest) (*ReloadPackageResponse, error)
	ReloadAllPackages(context.Context, *ReloadAllPackagesRequest) (*ReloadAllPackagesResponse, error)
	GetPackageById(context.Context, *GetPackageByIdRequest) (*GetPackageByIdResponse, error)
	GetPackageByOriginId(context.Context, *GetPackageByOriginIdRequest) (*GetPackageByOriginIdResponse, error)
	GetPackageListASCByLastId(context.Context, *GetPackageListASCByLastIdRequest) (*GetPackageListASCByLastIdResponse, error)
	ComputePackagesCombo(context.Context, *ComputePackageComboRequest) (*ComputePackageComboResponse, error)
	mustEmbedUnimplementedComputeEngineAPIServer()
}

// UnimplementedComputeEngineAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeEngineAPIServer struct{}

func (UnimplementedComputeEngineAPIServer) RegisterPackage(context.Context, *RegisterPackageRequest) (*RegisterPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPackage not implemented")
}
func (UnimplementedComputeEngineAPIServer) UploadPackage(context.Context, *UploadPackageRequest) (*UploadPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPackage not implemented")
}
func (UnimplementedComputeEngineAPIServer) ReloadPackage(context.Context, *ReloadPackageRequest) (*ReloadPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadPackage not implemented")
}
func (UnimplementedComputeEngineAPIServer) ReloadAllPackages(context.Context, *ReloadAllPackagesRequest) (*ReloadAllPackagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadAllPackages not implemented")
}
func (UnimplementedComputeEngineAPIServer) GetPackageById(context.Context, *GetPackageByIdRequest) (*GetPackageByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageById not implemented")
}
func (UnimplementedComputeEngineAPIServer) GetPackageByOriginId(context.Context, *GetPackageByOriginIdRequest) (*GetPackageByOriginIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageByOriginId not implemented")
}
func (UnimplementedComputeEngineAPIServer) GetPackageListASCByLastId(context.Context, *GetPackageListASCByLastIdRequest) (*GetPackageListASCByLastIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageListASCByLastId not implemented")
}
func (UnimplementedComputeEngineAPIServer) ComputePackagesCombo(context.Context, *ComputePackageComboRequest) (*ComputePackageComboResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputePackagesCombo not implemented")
}
func (UnimplementedComputeEngineAPIServer) mustEmbedUnimplementedComputeEngineAPIServer() {}
func (UnimplementedComputeEngineAPIServer) testEmbeddedByValue()                          {}

// UnsafeComputeEngineAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeEngineAPIServer will
// result in compilation errors.
type UnsafeComputeEngineAPIServer interface {
	mustEmbedUnimplementedComputeEngineAPIServer()
}

func RegisterComputeEngineAPIServer(s grpc.ServiceRegistrar, srv ComputeEngineAPIServer) {
	// If the following call panics, it indicates UnimplementedComputeEngineAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComputeEngineAPI_ServiceDesc, srv)
}

func _ComputeEngineAPI_RegisterPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeEngineAPIServer).RegisterPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeEngineAPI_RegisterPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeEngineAPIServer).RegisterPackage(ctx, req.(*RegisterPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeEngineAPI_UploadPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeEngineAPIServer).UploadPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeEngineAPI_UploadPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeEngineAPIServer).UploadPackage(ctx, req.(*UploadPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeEngineAPI_ReloadPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeEngineAPIServer).ReloadPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeEngineAPI_ReloadPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeEngineAPIServer).ReloadPackage(ctx, req.(*ReloadPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeEngineAPI_ReloadAllPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadAllPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeEngineAPIServer).ReloadAllPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeEngineAPI_ReloadAllPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeEngineAPIServer).ReloadAllPackages(ctx, req.(*ReloadAllPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeEngineAPI_GetPackageById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeEngineAPIServer).GetPackageById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeEngineAPI_GetPackageById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeEngineAPIServer).GetPackageById(ctx, req.(*GetPackageByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeEngineAPI_GetPackageByOriginId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageByOriginIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeEngineAPIServer).GetPackageByOriginId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeEngineAPI_GetPackageByOriginId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeEngineAPIServer).GetPackageByOriginId(ctx, req.(*GetPackageByOriginIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeEngineAPI_GetPackageListASCByLastId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageListASCByLastIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeEngineAPIServer).GetPackageListASCByLastId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeEngineAPI_GetPackageListASCByLastId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeEngineAPIServer).GetPackageListASCByLastId(ctx, req.(*GetPackageListASCByLastIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeEngineAPI_ComputePackagesCombo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputePackageComboRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeEngineAPIServer).ComputePackagesCombo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeEngineAPI_ComputePackagesCombo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeEngineAPIServer).ComputePackagesCombo(ctx, req.(*ComputePackageComboRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputeEngineAPI_ServiceDesc is the grpc.ServiceDesc for ComputeEngineAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputeEngineAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DataManagementPlatform_ComputeEngineAPI.ComputeEngineAPI",
	HandlerType: (*ComputeEngineAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPackage",
			Handler:    _ComputeEngineAPI_RegisterPackage_Handler,
		},
		{
			MethodName: "UploadPackage",
			Handler:    _ComputeEngineAPI_UploadPackage_Handler,
		},
		{
			MethodName: "ReloadPackage",
			Handler:    _ComputeEngineAPI_ReloadPackage_Handler,
		},
		{
			MethodName: "ReloadAllPackages",
			Handler:    _ComputeEngineAPI_ReloadAllPackages_Handler,
		},
		{
			MethodName: "GetPackageById",
			Handler:    _ComputeEngineAPI_GetPackageById_Handler,
		},
		{
			MethodName: "GetPackageByOriginId",
			Handler:    _ComputeEngineAPI_GetPackageByOriginId_Handler,
		},
		{
			MethodName: "GetPackageListASCByLastId",
			Handler:    _ComputeEngineAPI_GetPackageListASCByLastId_Handler,
		},
		{
			MethodName: "ComputePackagesCombo",
			Handler:    _ComputeEngineAPI_ComputePackagesCombo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "DataManagementPlatform_ComputeEngineAPI/DataManagementPlatform_ComputeEngineAPI.proto",
}
