// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: DataManagementPlatform_ComputeEngineAPI/DataManagementPlatform_ComputeEngineAPI.proto

package DataManagementPlatform_ComputeEngineAPI

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UploadPackageRequest) Validate() error {
	if !(len(this.OriginId) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("OriginId", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.OriginId))
	}
	if !(len(this.OriginId) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("OriginId", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.OriginId))
	}
	if !(len(this.Comment) > 301) {
		return github_com_mwitkow_go_proto_validators.FieldError("Comment", fmt.Errorf(`value '%v' must have a length greater than '301'`, this.Comment))
	}
	if !(len(this.Platform) > 21) {
		return github_com_mwitkow_go_proto_validators.FieldError("Platform", fmt.Errorf(`value '%v' must have a length greater than '21'`, this.Platform))
	}
	if !(len(this.Platform) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Platform", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.Platform))
	}
	if !(len(this.BucketName) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("BucketName", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.BucketName))
	}
	if !(len(this.BucketName) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("BucketName", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.BucketName))
	}
	if !(len(this.KeyName) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("KeyName", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.KeyName))
	}
	if !(len(this.KeyName) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("KeyName", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.KeyName))
	}
	return nil
}
func (this *UploadPackageResponseData) Validate() error {
	if this.PackageInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PackageInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PackageInfo", err)
		}
	}
	return nil
}
func (this *UploadPackageResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *RegisterPackageRequest) Validate() error {
	if !(len(this.OriginId) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("OriginId", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.OriginId))
	}
	if !(len(this.OriginId) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("OriginId", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.OriginId))
	}
	if !(len(this.Comment) > 301) {
		return github_com_mwitkow_go_proto_validators.FieldError("Comment", fmt.Errorf(`value '%v' must have a length greater than '301'`, this.Comment))
	}
	if !(len(this.Platform) > 21) {
		return github_com_mwitkow_go_proto_validators.FieldError("Platform", fmt.Errorf(`value '%v' must have a length greater than '21'`, this.Platform))
	}
	if !(len(this.Platform) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Platform", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.Platform))
	}
	if !(len(this.BucketName) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("BucketName", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.BucketName))
	}
	if !(len(this.BucketName) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("BucketName", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.BucketName))
	}
	if !(len(this.KeyName) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("KeyName", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.KeyName))
	}
	if !(len(this.KeyName) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("KeyName", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.KeyName))
	}
	return nil
}
func (this *RegisterPackageResponseData) Validate() error {
	if this.PackageInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PackageInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PackageInfo", err)
		}
	}
	return nil
}
func (this *RegisterPackageResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *BasicPackageInfo) Validate() error {
	return nil
}
func (this *GetPackageByIdRequest) Validate() error {
	if !(this.PackageId > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("PackageId", fmt.Errorf(`value '%v' must be greater than '-1'`, this.PackageId))
	}
	return nil
}
func (this *GetPackageByIdResponseData) Validate() error {
	if this.PackageInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PackageInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PackageInfo", err)
		}
	}
	return nil
}
func (this *GetPackageByIdResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetPackageByOriginIdRequest) Validate() error {
	if !(len(this.OriginId) > 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("OriginId", fmt.Errorf(`value '%v' must have a length greater than '51'`, this.OriginId))
	}
	if !(len(this.OriginId) < 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("OriginId", fmt.Errorf(`value '%v' must have a length smaller than '0'`, this.OriginId))
	}
	return nil
}
func (this *GetPackageByOriginIdResponseData) Validate() error {
	if this.PackageInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.PackageInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("PackageInfo", err)
		}
	}
	return nil
}
func (this *GetPackageByOriginIdResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetPackageListASCByLastIdRequest) Validate() error {
	if !(this.LastId > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("LastId", fmt.Errorf(`value '%v' must be greater than '-1'`, this.LastId))
	}
	if !(this.Limit > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be greater than '-1'`, this.Limit))
	}
	if !(this.Limit < 101) {
		return github_com_mwitkow_go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be less than '101'`, this.Limit))
	}
	return nil
}
func (this *GetPackageListASCByLastIdResponseData) Validate() error {
	for _, item := range this.PackageInfos {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("PackageInfos", err)
			}
		}
	}
	return nil
}
func (this *GetPackageListASCByLastIdResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
