// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: projectgeneratorapi/projectgeneratorapi.proto

package projectgeneratorapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectGeneratorAPI_GenerateProject_FullMethodName          = "/projectgeneratorapi.ProjectGeneratorAPI/GenerateProject"
	ProjectGeneratorAPI_DownloadGeneratedProject_FullMethodName = "/projectgeneratorapi.ProjectGeneratorAPI/DownloadGeneratedProject"
)

// ProjectGeneratorAPIClient is the client API for ProjectGeneratorAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectGeneratorAPIClient interface {
	GenerateProject(ctx context.Context, in *GenerateProjectRequest, opts ...grpc.CallOption) (*GenerateProjectResponse, error)
	DownloadGeneratedProject(ctx context.Context, in *DownloadGeneratedProjectRequest, opts ...grpc.CallOption) (*DownloadGeneratedProjectResponse, error)
}

type projectGeneratorAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectGeneratorAPIClient(cc grpc.ClientConnInterface) ProjectGeneratorAPIClient {
	return &projectGeneratorAPIClient{cc}
}

func (c *projectGeneratorAPIClient) GenerateProject(ctx context.Context, in *GenerateProjectRequest, opts ...grpc.CallOption) (*GenerateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateProjectResponse)
	err := c.cc.Invoke(ctx, ProjectGeneratorAPI_GenerateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectGeneratorAPIClient) DownloadGeneratedProject(ctx context.Context, in *DownloadGeneratedProjectRequest, opts ...grpc.CallOption) (*DownloadGeneratedProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadGeneratedProjectResponse)
	err := c.cc.Invoke(ctx, ProjectGeneratorAPI_DownloadGeneratedProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectGeneratorAPIServer is the server API for ProjectGeneratorAPI service.
// All implementations must embed UnimplementedProjectGeneratorAPIServer
// for forward compatibility.
type ProjectGeneratorAPIServer interface {
	GenerateProject(context.Context, *GenerateProjectRequest) (*GenerateProjectResponse, error)
	DownloadGeneratedProject(context.Context, *DownloadGeneratedProjectRequest) (*DownloadGeneratedProjectResponse, error)
	mustEmbedUnimplementedProjectGeneratorAPIServer()
}

// UnimplementedProjectGeneratorAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectGeneratorAPIServer struct{}

func (UnimplementedProjectGeneratorAPIServer) GenerateProject(context.Context, *GenerateProjectRequest) (*GenerateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateProject not implemented")
}
func (UnimplementedProjectGeneratorAPIServer) DownloadGeneratedProject(context.Context, *DownloadGeneratedProjectRequest) (*DownloadGeneratedProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadGeneratedProject not implemented")
}
func (UnimplementedProjectGeneratorAPIServer) mustEmbedUnimplementedProjectGeneratorAPIServer() {}
func (UnimplementedProjectGeneratorAPIServer) testEmbeddedByValue()                             {}

// UnsafeProjectGeneratorAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectGeneratorAPIServer will
// result in compilation errors.
type UnsafeProjectGeneratorAPIServer interface {
	mustEmbedUnimplementedProjectGeneratorAPIServer()
}

func RegisterProjectGeneratorAPIServer(s grpc.ServiceRegistrar, srv ProjectGeneratorAPIServer) {
	// If the following call panics, it indicates UnimplementedProjectGeneratorAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectGeneratorAPI_ServiceDesc, srv)
}

func _ProjectGeneratorAPI_GenerateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGeneratorAPIServer).GenerateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGeneratorAPI_GenerateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGeneratorAPIServer).GenerateProject(ctx, req.(*GenerateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectGeneratorAPI_DownloadGeneratedProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadGeneratedProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectGeneratorAPIServer).DownloadGeneratedProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectGeneratorAPI_DownloadGeneratedProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectGeneratorAPIServer).DownloadGeneratedProject(ctx, req.(*DownloadGeneratedProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectGeneratorAPI_ServiceDesc is the grpc.ServiceDesc for ProjectGeneratorAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectGeneratorAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projectgeneratorapi.ProjectGeneratorAPI",
	HandlerType: (*ProjectGeneratorAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateProject",
			Handler:    _ProjectGeneratorAPI_GenerateProject_Handler,
		},
		{
			MethodName: "DownloadGeneratedProject",
			Handler:    _ProjectGeneratorAPI_DownloadGeneratedProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "projectgeneratorapi/projectgeneratorapi.proto",
}
