// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: projectgeneratorapi/projectgeneratorapi.proto

package projectgeneratorapi

import (
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadGeneratedProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           string                 `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadGeneratedProjectRequest) Reset() {
	*x = DownloadGeneratedProjectRequest{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadGeneratedProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadGeneratedProjectRequest) ProtoMessage() {}

func (x *DownloadGeneratedProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadGeneratedProjectRequest.ProtoReflect.Descriptor instead.
func (*DownloadGeneratedProjectRequest) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadGeneratedProjectRequest) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

type GenerateProjectRequestComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateProjectRequestComponent) Reset() {
	*x = GenerateProjectRequestComponent{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectRequestComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectRequestComponent) ProtoMessage() {}

func (x *GenerateProjectRequestComponent) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectRequestComponent.ProtoReflect.Descriptor instead.
func (*GenerateProjectRequestComponent) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateProjectRequestComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateProjectRequestComponent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GenerateProjectRequestDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateProjectRequestDependency) Reset() {
	*x = GenerateProjectRequestDependency{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectRequestDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectRequestDependency) ProtoMessage() {}

func (x *GenerateProjectRequestDependency) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectRequestDependency.ProtoReflect.Descriptor instead.
func (*GenerateProjectRequestDependency) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateProjectRequestDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateProjectRequestDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GenerateProjectRequest struct {
	state                  protoimpl.MessageState              `protogen:"open.v1"`
	ProjectName            string                              `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectDescription     string                              `protobuf:"bytes,2,opt,name=project_description,json=projectDescription,proto3" json:"project_description,omitempty"`
	ProjectAppName         string                              `protobuf:"bytes,3,opt,name=project_app_name,json=projectAppName,proto3" json:"project_app_name,omitempty"`
	ProjectServerName      string                              `protobuf:"bytes,4,opt,name=project_server_name,json=projectServerName,proto3" json:"project_server_name,omitempty"`
	ProjectLanguage        string                              `protobuf:"bytes,5,opt,name=project_language,json=projectLanguage,proto3" json:"project_language,omitempty"`
	ProjectLanguageVersion string                              `protobuf:"bytes,6,opt,name=project_language_version,json=projectLanguageVersion,proto3" json:"project_language_version,omitempty"`
	ProjectDependencies    []*GenerateProjectRequestDependency `protobuf:"bytes,7,rep,name=project_dependencies,json=projectDependencies,proto3" json:"project_dependencies,omitempty"`
	ProjectComponents      []*GenerateProjectRequestComponent  `protobuf:"bytes,8,rep,name=project_components,json=projectComponents,proto3" json:"project_components,omitempty"`
	ProjectCvsUrl          string                              `protobuf:"bytes,9,opt,name=project_cvs_url,json=projectCvsUrl,proto3" json:"project_cvs_url,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GenerateProjectRequest) Reset() {
	*x = GenerateProjectRequest{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectRequest) ProtoMessage() {}

func (x *GenerateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectRequest.ProtoReflect.Descriptor instead.
func (*GenerateProjectRequest) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectDescription() string {
	if x != nil {
		return x.ProjectDescription
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectAppName() string {
	if x != nil {
		return x.ProjectAppName
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectServerName() string {
	if x != nil {
		return x.ProjectServerName
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectLanguage() string {
	if x != nil {
		return x.ProjectLanguage
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectLanguageVersion() string {
	if x != nil {
		return x.ProjectLanguageVersion
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectDependencies() []*GenerateProjectRequestDependency {
	if x != nil {
		return x.ProjectDependencies
	}
	return nil
}

func (x *GenerateProjectRequest) GetProjectComponents() []*GenerateProjectRequestComponent {
	if x != nil {
		return x.ProjectComponents
	}
	return nil
}

func (x *GenerateProjectRequest) GetProjectCvsUrl() string {
	if x != nil {
		return x.ProjectCvsUrl
	}
	return ""
}

type GenerateProjectResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           string                 `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateProjectResponseData) Reset() {
	*x = GenerateProjectResponseData{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectResponseData) ProtoMessage() {}

func (x *GenerateProjectResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectResponseData.ProtoReflect.Descriptor instead.
func (*GenerateProjectResponseData) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateProjectResponseData) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

type GenerateProjectResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	ErrCode       int32                        `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                       `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *GenerateProjectResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateProjectResponse) Reset() {
	*x = GenerateProjectResponse{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectResponse) ProtoMessage() {}

func (x *GenerateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectResponse.ProtoReflect.Descriptor instead.
func (*GenerateProjectResponse) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateProjectResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GenerateProjectResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GenerateProjectResponse) GetData() *GenerateProjectResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_projectgeneratorapi_projectgeneratorapi_proto protoreflect.FileDescriptor

const file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc = "" +
	"\n" +
	"-projectgeneratorapi/projectgeneratorapi.proto\x12\x13projectgeneratorapi\x1a+mwitkow/go-proto-validators/validator.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\"N\n" +
	"\x1fDownloadGeneratedProjectRequest\x12+\n" +
	"\x03seq\x18\x01 \x01(\tB\x19\xe2\xdf\x1f\x15\n" +
	"\x0f^[a-zA-Z0-9_]*$p\x00x3R\x03seq\"c\n" +
	"\x1fGenerateProjectRequestComponent\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x3R\x04name\x12\"\n" +
	"\aversion\x18\x02 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x\x15R\aversion\"d\n" +
	" GenerateProjectRequestDependency\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x3R\x04name\x12\"\n" +
	"\aversion\x18\x02 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x\x15R\aversion\"\xc0\x05\n" +
	"\x16GenerateProjectRequest\x12<\n" +
	"\fproject_name\x18\x01 \x01(\tB\x19\xe2\xdf\x1f\x15\n" +
	"\x0f^[a-zA-Z0-9_]*$p\x00x\x1fR\vprojectName\x12:\n" +
	"\x13project_description\x18\x02 \x01(\tB\t\xe2\xdf\x1f\x05p\x00x\xf5\x03R\x12projectDescription\x12C\n" +
	"\x10project_app_name\x18\x03 \x01(\tB\x19\xe2\xdf\x1f\x15\n" +
	"\x0f^[a-zA-Z0-9_]*$p\x00x\x1fR\x0eprojectAppName\x12I\n" +
	"\x13project_server_name\x18\x04 \x01(\tB\x19\xe2\xdf\x1f\x15\n" +
	"\x0f^[a-zA-Z0-9_]*$p\x00x\x1fR\x11projectServerName\x12D\n" +
	"\x10project_language\x18\x05 \x01(\tB\x19\xe2\xdf\x1f\x15\n" +
	"\x0f^[a-zA-Z0-9_]*$p\x00x\x1fR\x0fprojectLanguage\x12T\n" +
	"\x18project_language_version\x18\x06 \x01(\tB\x1a\xe2\xdf\x1f\x16\n" +
	"\x10^[a-zA-Z0-9_.]*$p\x00x\x1fR\x16projectLanguageVersion\x12h\n" +
	"\x14project_dependencies\x18\a \x03(\v25.projectgeneratorapi.GenerateProjectRequestDependencyR\x13projectDependencies\x12c\n" +
	"\x12project_components\x18\b \x03(\v24.projectgeneratorapi.GenerateProjectRequestComponentR\x11projectComponents\x121\n" +
	"\x0fproject_cvs_url\x18\t \x01(\tB\t\xe2\xdf\x1f\x05p\x00x\xc9\x01R\rprojectCvsUrl\"/\n" +
	"\x1bGenerateProjectResponseData\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\tR\x03seq\"\x93\x01\n" +
	"\x17GenerateProjectResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12D\n" +
	"\x04data\x18\x03 \x01(\v20.projectgeneratorapi.GenerateProjectResponseDataR\x04data2\xab\x02\n" +
	"\x13ProjectGeneratorAPI\x12\x8b\x01\n" +
	"\x0fGenerateProject\x12+.projectgeneratorapi.GenerateProjectRequest\x1a,.projectgeneratorapi.GenerateProjectResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/projects/generate\x12\x85\x01\n" +
	"\x18DownloadGeneratedProject\x124.projectgeneratorapi.DownloadGeneratedProjectRequest\x1a\x14.google.api.HttpBody\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/projects/downloadB,Z*./projectgeneratorapi/;projectgeneratorapib\x06proto3"

var (
	file_projectgeneratorapi_projectgeneratorapi_proto_rawDescOnce sync.Once
	file_projectgeneratorapi_projectgeneratorapi_proto_rawDescData []byte
)

func file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP() []byte {
	file_projectgeneratorapi_projectgeneratorapi_proto_rawDescOnce.Do(func() {
		file_projectgeneratorapi_projectgeneratorapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc), len(file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc)))
	})
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescData
}

var file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_projectgeneratorapi_projectgeneratorapi_proto_goTypes = []any{
	(*DownloadGeneratedProjectRequest)(nil),  // 0: projectgeneratorapi.DownloadGeneratedProjectRequest
	(*GenerateProjectRequestComponent)(nil),  // 1: projectgeneratorapi.GenerateProjectRequestComponent
	(*GenerateProjectRequestDependency)(nil), // 2: projectgeneratorapi.GenerateProjectRequestDependency
	(*GenerateProjectRequest)(nil),           // 3: projectgeneratorapi.GenerateProjectRequest
	(*GenerateProjectResponseData)(nil),      // 4: projectgeneratorapi.GenerateProjectResponseData
	(*GenerateProjectResponse)(nil),          // 5: projectgeneratorapi.GenerateProjectResponse
	(*httpbody.HttpBody)(nil),                // 6: google.api.HttpBody
}
var file_projectgeneratorapi_projectgeneratorapi_proto_depIdxs = []int32{
	2, // 0: projectgeneratorapi.GenerateProjectRequest.project_dependencies:type_name -> projectgeneratorapi.GenerateProjectRequestDependency
	1, // 1: projectgeneratorapi.GenerateProjectRequest.project_components:type_name -> projectgeneratorapi.GenerateProjectRequestComponent
	4, // 2: projectgeneratorapi.GenerateProjectResponse.data:type_name -> projectgeneratorapi.GenerateProjectResponseData
	3, // 3: projectgeneratorapi.ProjectGeneratorAPI.GenerateProject:input_type -> projectgeneratorapi.GenerateProjectRequest
	0, // 4: projectgeneratorapi.ProjectGeneratorAPI.DownloadGeneratedProject:input_type -> projectgeneratorapi.DownloadGeneratedProjectRequest
	5, // 5: projectgeneratorapi.ProjectGeneratorAPI.GenerateProject:output_type -> projectgeneratorapi.GenerateProjectResponse
	6, // 6: projectgeneratorapi.ProjectGeneratorAPI.DownloadGeneratedProject:output_type -> google.api.HttpBody
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_projectgeneratorapi_projectgeneratorapi_proto_init() }
func file_projectgeneratorapi_projectgeneratorapi_proto_init() {
	if File_projectgeneratorapi_projectgeneratorapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc), len(file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projectgeneratorapi_projectgeneratorapi_proto_goTypes,
		DependencyIndexes: file_projectgeneratorapi_projectgeneratorapi_proto_depIdxs,
		MessageInfos:      file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes,
	}.Build()
	File_projectgeneratorapi_projectgeneratorapi_proto = out.File
	file_projectgeneratorapi_projectgeneratorapi_proto_goTypes = nil
	file_projectgeneratorapi_projectgeneratorapi_proto_depIdxs = nil
}
