// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: projectgeneratorapi/projectgeneratorapi.proto

package projectgeneratorapi

import (
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateProjectRequestDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateProjectRequestDependency) Reset() {
	*x = GenerateProjectRequestDependency{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectRequestDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectRequestDependency) ProtoMessage() {}

func (x *GenerateProjectRequestDependency) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectRequestDependency.ProtoReflect.Descriptor instead.
func (*GenerateProjectRequestDependency) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateProjectRequestDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateProjectRequestDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GenerateProjectRequest struct {
	state               protoimpl.MessageState              `protogen:"open.v1"`
	ProjectName         string                              `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectDescription  string                              `protobuf:"bytes,2,opt,name=project_description,json=projectDescription,proto3" json:"project_description,omitempty"`
	ProjectAppName      string                              `protobuf:"bytes,3,opt,name=project_app_name,json=projectAppName,proto3" json:"project_app_name,omitempty"`
	ProjectServiceName  string                              `protobuf:"bytes,4,opt,name=project_service_name,json=projectServiceName,proto3" json:"project_service_name,omitempty"`
	ProjectDependencies []*GenerateProjectRequestDependency `protobuf:"bytes,5,rep,name=project_dependencies,json=projectDependencies,proto3" json:"project_dependencies,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GenerateProjectRequest) Reset() {
	*x = GenerateProjectRequest{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectRequest) ProtoMessage() {}

func (x *GenerateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectRequest.ProtoReflect.Descriptor instead.
func (*GenerateProjectRequest) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectDescription() string {
	if x != nil {
		return x.ProjectDescription
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectAppName() string {
	if x != nil {
		return x.ProjectAppName
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectServiceName() string {
	if x != nil {
		return x.ProjectServiceName
	}
	return ""
}

func (x *GenerateProjectRequest) GetProjectDependencies() []*GenerateProjectRequestDependency {
	if x != nil {
		return x.ProjectDependencies
	}
	return nil
}

type GenerateProjectRequestData struct {
	state               protoimpl.MessageState              `protogen:"open.v1"`
	ProjectName         string                              `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectDescription  string                              `protobuf:"bytes,2,opt,name=project_description,json=projectDescription,proto3" json:"project_description,omitempty"`
	ProjectAppName      string                              `protobuf:"bytes,3,opt,name=project_app_name,json=projectAppName,proto3" json:"project_app_name,omitempty"`
	ProjectServiceName  string                              `protobuf:"bytes,4,opt,name=project_service_name,json=projectServiceName,proto3" json:"project_service_name,omitempty"`
	ProjectDependencies []*GenerateProjectRequestDependency `protobuf:"bytes,5,rep,name=project_dependencies,json=projectDependencies,proto3" json:"project_dependencies,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GenerateProjectRequestData) Reset() {
	*x = GenerateProjectRequestData{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectRequestData) ProtoMessage() {}

func (x *GenerateProjectRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectRequestData.ProtoReflect.Descriptor instead.
func (*GenerateProjectRequestData) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateProjectRequestData) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *GenerateProjectRequestData) GetProjectDescription() string {
	if x != nil {
		return x.ProjectDescription
	}
	return ""
}

func (x *GenerateProjectRequestData) GetProjectAppName() string {
	if x != nil {
		return x.ProjectAppName
	}
	return ""
}

func (x *GenerateProjectRequestData) GetProjectServiceName() string {
	if x != nil {
		return x.ProjectServiceName
	}
	return ""
}

func (x *GenerateProjectRequestData) GetProjectDependencies() []*GenerateProjectRequestDependency {
	if x != nil {
		return x.ProjectDependencies
	}
	return nil
}

type GenerateProjectResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ErrCode       int32                       `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                      `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *GenerateProjectRequestData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateProjectResponse) Reset() {
	*x = GenerateProjectResponse{}
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateProjectResponse) ProtoMessage() {}

func (x *GenerateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateProjectResponse.ProtoReflect.Descriptor instead.
func (*GenerateProjectResponse) Descriptor() ([]byte, []int) {
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateProjectResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GenerateProjectResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GenerateProjectResponse) GetData() *GenerateProjectRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_projectgeneratorapi_projectgeneratorapi_proto protoreflect.FileDescriptor

const file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc = "" +
	"\n" +
	"-projectgeneratorapi/projectgeneratorapi.proto\x12\x13projectgeneratorapi\x1a+mwitkow/go-proto-validators/validator.proto\x1a\x1cgoogle/api/annotations.proto\"d\n" +
	" GenerateProjectRequestDependency\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x3R\x04name\x12\"\n" +
	"\aversion\x18\x02 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x\x15R\aversion\"\x8d\x03\n" +
	"\x16GenerateProjectRequest\x12+\n" +
	"\fproject_name\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x\x1fR\vprojectName\x12:\n" +
	"\x13project_description\x18\x02 \x01(\tB\t\xe2\xdf\x1f\x05p\x00x\xf5\x03R\x12projectDescription\x12K\n" +
	"\x10project_app_name\x18\x03 \x01(\tB!\xe2\xdf\x1f\x1d\n" +
	"\x17^[a-zA-Z][a-zA-Z0-9_]*$p\x00x\x1fR\x0eprojectAppName\x12S\n" +
	"\x14project_service_name\x18\x04 \x01(\tB!\xe2\xdf\x1f\x1d\n" +
	"\x17^[a-zA-Z][a-zA-Z0-9_]*$p\x00x\x1fR\x12projectServiceName\x12h\n" +
	"\x14project_dependencies\x18\x05 \x03(\v25.projectgeneratorapi.GenerateProjectRequestDependencyR\x13projectDependencies\"\xb6\x02\n" +
	"\x1aGenerateProjectRequestData\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12/\n" +
	"\x13project_description\x18\x02 \x01(\tR\x12projectDescription\x12(\n" +
	"\x10project_app_name\x18\x03 \x01(\tR\x0eprojectAppName\x120\n" +
	"\x14project_service_name\x18\x04 \x01(\tR\x12projectServiceName\x12h\n" +
	"\x14project_dependencies\x18\x05 \x03(\v25.projectgeneratorapi.GenerateProjectRequestDependencyR\x13projectDependencies\"\x92\x01\n" +
	"\x17GenerateProjectResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12C\n" +
	"\x04data\x18\x03 \x01(\v2/.projectgeneratorapi.GenerateProjectRequestDataR\x04data2\xa3\x01\n" +
	"\x13ProjectGeneratorAPI\x12\x8b\x01\n" +
	"\x0fGenerateProject\x12+.projectgeneratorapi.GenerateProjectRequest\x1a,.projectgeneratorapi.GenerateProjectResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/projects/generateB\x18Z\x16./;projectgeneratorapib\x06proto3"

var (
	file_projectgeneratorapi_projectgeneratorapi_proto_rawDescOnce sync.Once
	file_projectgeneratorapi_projectgeneratorapi_proto_rawDescData []byte
)

func file_projectgeneratorapi_projectgeneratorapi_proto_rawDescGZIP() []byte {
	file_projectgeneratorapi_projectgeneratorapi_proto_rawDescOnce.Do(func() {
		file_projectgeneratorapi_projectgeneratorapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc), len(file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc)))
	})
	return file_projectgeneratorapi_projectgeneratorapi_proto_rawDescData
}

var file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_projectgeneratorapi_projectgeneratorapi_proto_goTypes = []any{
	(*GenerateProjectRequestDependency)(nil), // 0: projectgeneratorapi.GenerateProjectRequestDependency
	(*GenerateProjectRequest)(nil),           // 1: projectgeneratorapi.GenerateProjectRequest
	(*GenerateProjectRequestData)(nil),       // 2: projectgeneratorapi.GenerateProjectRequestData
	(*GenerateProjectResponse)(nil),          // 3: projectgeneratorapi.GenerateProjectResponse
}
var file_projectgeneratorapi_projectgeneratorapi_proto_depIdxs = []int32{
	0, // 0: projectgeneratorapi.GenerateProjectRequest.project_dependencies:type_name -> projectgeneratorapi.GenerateProjectRequestDependency
	0, // 1: projectgeneratorapi.GenerateProjectRequestData.project_dependencies:type_name -> projectgeneratorapi.GenerateProjectRequestDependency
	2, // 2: projectgeneratorapi.GenerateProjectResponse.data:type_name -> projectgeneratorapi.GenerateProjectRequestData
	1, // 3: projectgeneratorapi.ProjectGeneratorAPI.GenerateProject:input_type -> projectgeneratorapi.GenerateProjectRequest
	3, // 4: projectgeneratorapi.ProjectGeneratorAPI.GenerateProject:output_type -> projectgeneratorapi.GenerateProjectResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_projectgeneratorapi_projectgeneratorapi_proto_init() }
func file_projectgeneratorapi_projectgeneratorapi_proto_init() {
	if File_projectgeneratorapi_projectgeneratorapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc), len(file_projectgeneratorapi_projectgeneratorapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projectgeneratorapi_projectgeneratorapi_proto_goTypes,
		DependencyIndexes: file_projectgeneratorapi_projectgeneratorapi_proto_depIdxs,
		MessageInfos:      file_projectgeneratorapi_projectgeneratorapi_proto_msgTypes,
	}.Build()
	File_projectgeneratorapi_projectgeneratorapi_proto = out.File
	file_projectgeneratorapi_projectgeneratorapi_proto_goTypes = nil
	file_projectgeneratorapi_projectgeneratorapi_proto_depIdxs = nil
}
