// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: projectgeneratorapi/projectgeneratorapi.proto

package projectgeneratorapi

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_DownloadGeneratedProjectRequest_Seq = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9_]*$`)

func (this *DownloadGeneratedProjectRequest) Validate() error {
	if !_regex_DownloadGeneratedProjectRequest_Seq.MatchString(this.Seq) {
		return github_com_mwitkow_go_proto_validators.FieldError("Seq", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z][a-zA-Z0-9_]*$"`, this.Seq))
	}
	if !(len(this.Seq) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Seq", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Seq))
	}
	if !(len(this.Seq) < 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("Seq", fmt.Errorf(`value '%v' must have a length smaller than '51'`, this.Seq))
	}
	return nil
}
func (this *DownloadGeneratedProjectResponseData) Validate() error {
	return nil
}
func (this *DownloadGeneratedProjectResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GenerateProjectRequestComponent) Validate() error {
	if !(len(this.Name) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Name))
	}
	if !(len(this.Name) < 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length smaller than '51'`, this.Name))
	}
	if !(len(this.Version) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Version", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Version))
	}
	if !(len(this.Version) < 21) {
		return github_com_mwitkow_go_proto_validators.FieldError("Version", fmt.Errorf(`value '%v' must have a length smaller than '21'`, this.Version))
	}
	return nil
}
func (this *GenerateProjectRequestDependency) Validate() error {
	if !(len(this.Name) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Name))
	}
	if !(len(this.Name) < 51) {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must have a length smaller than '51'`, this.Name))
	}
	if !(len(this.Version) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Version", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Version))
	}
	if !(len(this.Version) < 21) {
		return github_com_mwitkow_go_proto_validators.FieldError("Version", fmt.Errorf(`value '%v' must have a length smaller than '21'`, this.Version))
	}
	return nil
}

var _regex_GenerateProjectRequest_ProjectAppName = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9_]*$`)
var _regex_GenerateProjectRequest_ProjectServerName = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9_]*$`)

func (this *GenerateProjectRequest) Validate() error {
	if !(len(this.ProjectName) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectName", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.ProjectName))
	}
	if !(len(this.ProjectName) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectName", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.ProjectName))
	}
	if !(len(this.ProjectDescription) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectDescription", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.ProjectDescription))
	}
	if !(len(this.ProjectDescription) < 501) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectDescription", fmt.Errorf(`value '%v' must have a length smaller than '501'`, this.ProjectDescription))
	}
	if !_regex_GenerateProjectRequest_ProjectAppName.MatchString(this.ProjectAppName) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectAppName", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z][a-zA-Z0-9_]*$"`, this.ProjectAppName))
	}
	if !(len(this.ProjectAppName) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectAppName", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.ProjectAppName))
	}
	if !(len(this.ProjectAppName) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectAppName", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.ProjectAppName))
	}
	if !_regex_GenerateProjectRequest_ProjectServerName.MatchString(this.ProjectServerName) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectServerName", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z][a-zA-Z0-9_]*$"`, this.ProjectServerName))
	}
	if !(len(this.ProjectServerName) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectServerName", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.ProjectServerName))
	}
	if !(len(this.ProjectServerName) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectServerName", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.ProjectServerName))
	}
	if !(len(this.ProjectLanguage) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectLanguage", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.ProjectLanguage))
	}
	if !(len(this.ProjectLanguage) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectLanguage", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.ProjectLanguage))
	}
	if !(len(this.ProjectLanguageVersion) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectLanguageVersion", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.ProjectLanguageVersion))
	}
	if !(len(this.ProjectLanguageVersion) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectLanguageVersion", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.ProjectLanguageVersion))
	}
	for _, item := range this.ProjectDependencies {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ProjectDependencies", err)
			}
		}
	}
	for _, item := range this.ProjectComponents {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ProjectComponents", err)
			}
		}
	}
	return nil
}
func (this *GenerateProjectResponseData) Validate() error {
	return nil
}
func (this *GenerateProjectResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
