// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: devicemanagementplatformapi/devicemanagementplatformapi.proto

package devicemanagementplatformapi

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *DeviceInfo) Validate() error {
	return nil
}
func (this *QueryDeviceByNoRequest) Validate() error {
	if !(len(this.DeviceNo) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("DeviceNo", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.DeviceNo))
	}
	if !(len(this.DeviceNo) < 100) {
		return github_com_mwitkow_go_proto_validators.FieldError("DeviceNo", fmt.Errorf(`value '%v' must have a length smaller than '100'`, this.DeviceNo))
	}
	return nil
}
func (this *QueryDeviceByNoResponseData) Validate() error {
	if this.DeviceInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.DeviceInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("DeviceInfo", err)
		}
	}
	return nil
}
func (this *QueryDeviceByNoResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *QueryDeviceByIdRequest) Validate() error {
	if !(this.DeviceId > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("DeviceId", fmt.Errorf(`value '%v' must be greater than '-1'`, this.DeviceId))
	}
	return nil
}
func (this *QueryDeviceByIdResponseData) Validate() error {
	if this.DeviceInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.DeviceInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("DeviceInfo", err)
		}
	}
	return nil
}
func (this *QueryDeviceByIdResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *RegisterDeviceRequest) Validate() error {
	if !(len(this.DeviceNo) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("DeviceNo", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.DeviceNo))
	}
	if !(len(this.DeviceNo) < 100) {
		return github_com_mwitkow_go_proto_validators.FieldError("DeviceNo", fmt.Errorf(`value '%v' must have a length smaller than '100'`, this.DeviceNo))
	}
	return nil
}
func (this *RegisterDeviceResponseData) Validate() error {
	if this.DeviceInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.DeviceInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("DeviceInfo", err)
		}
	}
	return nil
}
func (this *RegisterDeviceResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
