// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: devicemanagementplatformapi/devicemanagementplatformapi.proto

package devicemanagementplatformapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceManagementPlatformAPI_QueryDeviceByNo_FullMethodName = "/devicemanagementplatformapi.DeviceManagementPlatformAPI/QueryDeviceByNo"
	DeviceManagementPlatformAPI_QueryDeviceById_FullMethodName = "/devicemanagementplatformapi.DeviceManagementPlatformAPI/QueryDeviceById"
	DeviceManagementPlatformAPI_RegisterDevice_FullMethodName  = "/devicemanagementplatformapi.DeviceManagementPlatformAPI/RegisterDevice"
)

// DeviceManagementPlatformAPIClient is the client API for DeviceManagementPlatformAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceManagementPlatformAPIClient interface {
	QueryDeviceByNo(ctx context.Context, in *QueryDeviceByNoRequest, opts ...grpc.CallOption) (*QueryDeviceByNoResponse, error)
	QueryDeviceById(ctx context.Context, in *QueryDeviceByIdRequest, opts ...grpc.CallOption) (*QueryDeviceByIdResponse, error)
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
}

type deviceManagementPlatformAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceManagementPlatformAPIClient(cc grpc.ClientConnInterface) DeviceManagementPlatformAPIClient {
	return &deviceManagementPlatformAPIClient{cc}
}

func (c *deviceManagementPlatformAPIClient) QueryDeviceByNo(ctx context.Context, in *QueryDeviceByNoRequest, opts ...grpc.CallOption) (*QueryDeviceByNoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDeviceByNoResponse)
	err := c.cc.Invoke(ctx, DeviceManagementPlatformAPI_QueryDeviceByNo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceManagementPlatformAPIClient) QueryDeviceById(ctx context.Context, in *QueryDeviceByIdRequest, opts ...grpc.CallOption) (*QueryDeviceByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDeviceByIdResponse)
	err := c.cc.Invoke(ctx, DeviceManagementPlatformAPI_QueryDeviceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceManagementPlatformAPIClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceManagementPlatformAPI_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceManagementPlatformAPIServer is the server API for DeviceManagementPlatformAPI service.
// All implementations must embed UnimplementedDeviceManagementPlatformAPIServer
// for forward compatibility.
type DeviceManagementPlatformAPIServer interface {
	QueryDeviceByNo(context.Context, *QueryDeviceByNoRequest) (*QueryDeviceByNoResponse, error)
	QueryDeviceById(context.Context, *QueryDeviceByIdRequest) (*QueryDeviceByIdResponse, error)
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	mustEmbedUnimplementedDeviceManagementPlatformAPIServer()
}

// UnimplementedDeviceManagementPlatformAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceManagementPlatformAPIServer struct{}

func (UnimplementedDeviceManagementPlatformAPIServer) QueryDeviceByNo(context.Context, *QueryDeviceByNoRequest) (*QueryDeviceByNoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryDeviceByNo not implemented")
}
func (UnimplementedDeviceManagementPlatformAPIServer) QueryDeviceById(context.Context, *QueryDeviceByIdRequest) (*QueryDeviceByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryDeviceById not implemented")
}
func (UnimplementedDeviceManagementPlatformAPIServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedDeviceManagementPlatformAPIServer) mustEmbedUnimplementedDeviceManagementPlatformAPIServer() {
}
func (UnimplementedDeviceManagementPlatformAPIServer) testEmbeddedByValue() {}

// UnsafeDeviceManagementPlatformAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceManagementPlatformAPIServer will
// result in compilation errors.
type UnsafeDeviceManagementPlatformAPIServer interface {
	mustEmbedUnimplementedDeviceManagementPlatformAPIServer()
}

func RegisterDeviceManagementPlatformAPIServer(s grpc.ServiceRegistrar, srv DeviceManagementPlatformAPIServer) {
	// If the following call panics, it indicates UnimplementedDeviceManagementPlatformAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceManagementPlatformAPI_ServiceDesc, srv)
}

func _DeviceManagementPlatformAPI_QueryDeviceByNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeviceByNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagementPlatformAPIServer).QueryDeviceByNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceManagementPlatformAPI_QueryDeviceByNo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagementPlatformAPIServer).QueryDeviceByNo(ctx, req.(*QueryDeviceByNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceManagementPlatformAPI_QueryDeviceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDeviceByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagementPlatformAPIServer).QueryDeviceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceManagementPlatformAPI_QueryDeviceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagementPlatformAPIServer).QueryDeviceById(ctx, req.(*QueryDeviceByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceManagementPlatformAPI_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagementPlatformAPIServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceManagementPlatformAPI_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagementPlatformAPIServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceManagementPlatformAPI_ServiceDesc is the grpc.ServiceDesc for DeviceManagementPlatformAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceManagementPlatformAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicemanagementplatformapi.DeviceManagementPlatformAPI",
	HandlerType: (*DeviceManagementPlatformAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDeviceByNo",
			Handler:    _DeviceManagementPlatformAPI_QueryDeviceByNo_Handler,
		},
		{
			MethodName: "QueryDeviceById",
			Handler:    _DeviceManagementPlatformAPI_QueryDeviceById_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _DeviceManagementPlatformAPI_RegisterDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devicemanagementplatformapi/devicemanagementplatformapi.proto",
}
