// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: devicemanagementplatformapi/devicemanagementplatformapi.proto

package devicemanagementplatformapi

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int64                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceNo      string                 `protobuf:"bytes,2,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	RegisterTime  int64                  `protobuf:"varint,3,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceInfo) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

func (x *DeviceInfo) GetRegisterTime() int64 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

type QueryDeviceByNoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceNo      string                 `protobuf:"bytes,1,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByNoRequest) Reset() {
	*x = QueryDeviceByNoRequest{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByNoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByNoRequest) ProtoMessage() {}

func (x *QueryDeviceByNoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByNoRequest.ProtoReflect.Descriptor instead.
func (*QueryDeviceByNoRequest) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{1}
}

func (x *QueryDeviceByNoRequest) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

type QueryDeviceByNoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByNoResponse) Reset() {
	*x = QueryDeviceByNoResponse{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByNoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByNoResponse) ProtoMessage() {}

func (x *QueryDeviceByNoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByNoResponse.ProtoReflect.Descriptor instead.
func (*QueryDeviceByNoResponse) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{2}
}

func (x *QueryDeviceByNoResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type QueryDeviceByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int64                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByIdRequest) Reset() {
	*x = QueryDeviceByIdRequest{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByIdRequest) ProtoMessage() {}

func (x *QueryDeviceByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByIdRequest.ProtoReflect.Descriptor instead.
func (*QueryDeviceByIdRequest) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{3}
}

func (x *QueryDeviceByIdRequest) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type QueryDeviceByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByIdResponse) Reset() {
	*x = QueryDeviceByIdResponse{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByIdResponse) ProtoMessage() {}

func (x *QueryDeviceByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByIdResponse.ProtoReflect.Descriptor instead.
func (*QueryDeviceByIdResponse) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{4}
}

func (x *QueryDeviceByIdResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceNo      string                 `protobuf:"bytes,1,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterDeviceRequest) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterDeviceResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

var File_devicemanagementplatformapi_devicemanagementplatformapi_proto protoreflect.FileDescriptor

const file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc = "" +
	"\n" +
	"=devicemanagementplatformapi/devicemanagementplatformapi.proto\x12\x1bdevicemanagementplatformapi\x1a\x1bbuf/validate/validate.proto\"k\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x03R\bdeviceId\x12\x1b\n" +
	"\tdevice_no\x18\x02 \x01(\tR\bdeviceNo\x12#\n" +
	"\rregister_time\x18\x03 \x01(\x03R\fregisterTime\"@\n" +
	"\x16QueryDeviceByNoRequest\x12&\n" +
	"\tdevice_no\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\bdeviceNo\"c\n" +
	"\x17QueryDeviceByNoResponse\x12H\n" +
	"\vdevice_info\x18\x01 \x01(\v2'.devicemanagementplatformapi.DeviceInfoR\n" +
	"deviceInfo\">\n" +
	"\x16QueryDeviceByIdRequest\x12$\n" +
	"\tdevice_id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bdeviceId\"c\n" +
	"\x17QueryDeviceByIdResponse\x12H\n" +
	"\vdevice_info\x18\x01 \x01(\v2'.devicemanagementplatformapi.DeviceInfoR\n" +
	"deviceInfo\"?\n" +
	"\x15RegisterDeviceRequest\x12&\n" +
	"\tdevice_no\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\bdeviceNo\"b\n" +
	"\x16RegisterDeviceResponse\x12H\n" +
	"\vdevice_info\x18\x01 \x01(\v2'.devicemanagementplatformapi.DeviceInfoR\n" +
	"deviceInfo2\x94\x03\n" +
	"\x1bDeviceManagementPlatformAPI\x12|\n" +
	"\x0fQueryDeviceByNo\x123.devicemanagementplatformapi.QueryDeviceByNoRequest\x1a4.devicemanagementplatformapi.QueryDeviceByNoResponse\x12|\n" +
	"\x0fQueryDeviceById\x123.devicemanagementplatformapi.QueryDeviceByIdRequest\x1a4.devicemanagementplatformapi.QueryDeviceByIdResponse\x12y\n" +
	"\x0eRegisterDevice\x122.devicemanagementplatformapi.RegisterDeviceRequest\x1a3.devicemanagementplatformapi.RegisterDeviceResponseB Z\x1e./;devicemanagementplatformapib\x06proto3"

var (
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescOnce sync.Once
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescData []byte
)

func file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP() []byte {
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescOnce.Do(func() {
		file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc), len(file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc)))
	})
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescData
}

var file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_devicemanagementplatformapi_devicemanagementplatformapi_proto_goTypes = []any{
	(*DeviceInfo)(nil),              // 0: devicemanagementplatformapi.DeviceInfo
	(*QueryDeviceByNoRequest)(nil),  // 1: devicemanagementplatformapi.QueryDeviceByNoRequest
	(*QueryDeviceByNoResponse)(nil), // 2: devicemanagementplatformapi.QueryDeviceByNoResponse
	(*QueryDeviceByIdRequest)(nil),  // 3: devicemanagementplatformapi.QueryDeviceByIdRequest
	(*QueryDeviceByIdResponse)(nil), // 4: devicemanagementplatformapi.QueryDeviceByIdResponse
	(*RegisterDeviceRequest)(nil),   // 5: devicemanagementplatformapi.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),  // 6: devicemanagementplatformapi.RegisterDeviceResponse
}
var file_devicemanagementplatformapi_devicemanagementplatformapi_proto_depIdxs = []int32{
	0, // 0: devicemanagementplatformapi.QueryDeviceByNoResponse.device_info:type_name -> devicemanagementplatformapi.DeviceInfo
	0, // 1: devicemanagementplatformapi.QueryDeviceByIdResponse.device_info:type_name -> devicemanagementplatformapi.DeviceInfo
	0, // 2: devicemanagementplatformapi.RegisterDeviceResponse.device_info:type_name -> devicemanagementplatformapi.DeviceInfo
	1, // 3: devicemanagementplatformapi.DeviceManagementPlatformAPI.QueryDeviceByNo:input_type -> devicemanagementplatformapi.QueryDeviceByNoRequest
	3, // 4: devicemanagementplatformapi.DeviceManagementPlatformAPI.QueryDeviceById:input_type -> devicemanagementplatformapi.QueryDeviceByIdRequest
	5, // 5: devicemanagementplatformapi.DeviceManagementPlatformAPI.RegisterDevice:input_type -> devicemanagementplatformapi.RegisterDeviceRequest
	2, // 6: devicemanagementplatformapi.DeviceManagementPlatformAPI.QueryDeviceByNo:output_type -> devicemanagementplatformapi.QueryDeviceByNoResponse
	4, // 7: devicemanagementplatformapi.DeviceManagementPlatformAPI.QueryDeviceById:output_type -> devicemanagementplatformapi.QueryDeviceByIdResponse
	6, // 8: devicemanagementplatformapi.DeviceManagementPlatformAPI.RegisterDevice:output_type -> devicemanagementplatformapi.RegisterDeviceResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_devicemanagementplatformapi_devicemanagementplatformapi_proto_init() }
func file_devicemanagementplatformapi_devicemanagementplatformapi_proto_init() {
	if File_devicemanagementplatformapi_devicemanagementplatformapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc), len(file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devicemanagementplatformapi_devicemanagementplatformapi_proto_goTypes,
		DependencyIndexes: file_devicemanagementplatformapi_devicemanagementplatformapi_proto_depIdxs,
		MessageInfos:      file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes,
	}.Build()
	File_devicemanagementplatformapi_devicemanagementplatformapi_proto = out.File
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_goTypes = nil
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_depIdxs = nil
}
