// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: devicemanagementplatformapi/devicemanagementplatformapi.proto

package devicemanagementplatformapi

import (
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int64                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceNo      string                 `protobuf:"bytes,2,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	RegisterTime  int64                  `protobuf:"varint,3,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceInfo) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

func (x *DeviceInfo) GetRegisterTime() int64 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

type QueryDeviceByNoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceNo      string                 `protobuf:"bytes,1,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByNoRequest) Reset() {
	*x = QueryDeviceByNoRequest{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByNoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByNoRequest) ProtoMessage() {}

func (x *QueryDeviceByNoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByNoRequest.ProtoReflect.Descriptor instead.
func (*QueryDeviceByNoRequest) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{1}
}

func (x *QueryDeviceByNoRequest) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

type QueryDeviceByNoResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByNoResponseData) Reset() {
	*x = QueryDeviceByNoResponseData{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByNoResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByNoResponseData) ProtoMessage() {}

func (x *QueryDeviceByNoResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByNoResponseData.ProtoReflect.Descriptor instead.
func (*QueryDeviceByNoResponseData) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{2}
}

func (x *QueryDeviceByNoResponseData) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type QueryDeviceByNoResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	ErrCode       int32                        `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                       `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *QueryDeviceByNoResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByNoResponse) Reset() {
	*x = QueryDeviceByNoResponse{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByNoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByNoResponse) ProtoMessage() {}

func (x *QueryDeviceByNoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByNoResponse.ProtoReflect.Descriptor instead.
func (*QueryDeviceByNoResponse) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{3}
}

func (x *QueryDeviceByNoResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *QueryDeviceByNoResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *QueryDeviceByNoResponse) GetData() *QueryDeviceByNoResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryDeviceByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int64                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByIdRequest) Reset() {
	*x = QueryDeviceByIdRequest{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByIdRequest) ProtoMessage() {}

func (x *QueryDeviceByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByIdRequest.ProtoReflect.Descriptor instead.
func (*QueryDeviceByIdRequest) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{4}
}

func (x *QueryDeviceByIdRequest) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type QueryDeviceByIdResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByIdResponseData) Reset() {
	*x = QueryDeviceByIdResponseData{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByIdResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByIdResponseData) ProtoMessage() {}

func (x *QueryDeviceByIdResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByIdResponseData.ProtoReflect.Descriptor instead.
func (*QueryDeviceByIdResponseData) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{5}
}

func (x *QueryDeviceByIdResponseData) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type QueryDeviceByIdResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	ErrCode       int32                        `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                       `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *QueryDeviceByIdResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDeviceByIdResponse) Reset() {
	*x = QueryDeviceByIdResponse{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDeviceByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDeviceByIdResponse) ProtoMessage() {}

func (x *QueryDeviceByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDeviceByIdResponse.ProtoReflect.Descriptor instead.
func (*QueryDeviceByIdResponse) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{6}
}

func (x *QueryDeviceByIdResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *QueryDeviceByIdResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *QueryDeviceByIdResponse) GetData() *QueryDeviceByIdResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceNo      string                 `protobuf:"bytes,1,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterDeviceRequest) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

type RegisterDeviceResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponseData) Reset() {
	*x = RegisterDeviceResponseData{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponseData) ProtoMessage() {}

func (x *RegisterDeviceResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponseData.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponseData) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterDeviceResponseData) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	ErrCode       int32                       `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                      `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *RegisterDeviceResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterDeviceResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *RegisterDeviceResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *RegisterDeviceResponse) GetData() *RegisterDeviceResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_devicemanagementplatformapi_devicemanagementplatformapi_proto protoreflect.FileDescriptor

const file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc = "" +
	"\n" +
	"=devicemanagementplatformapi/devicemanagementplatformapi.proto\x12\x1bdevicemanagementplatformapi\x1a+mwitkow/go-proto-validators/validator.proto\x1a\x1cgoogle/api/annotations.proto\"k\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x03R\bdeviceId\x12\x1b\n" +
	"\tdevice_no\x18\x02 \x01(\tR\bdeviceNo\x12#\n" +
	"\rregister_time\x18\x03 \x01(\x03R\fregisterTime\"?\n" +
	"\x16QueryDeviceByNoRequest\x12%\n" +
	"\tdevice_no\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p\x00xdR\bdeviceNo\"g\n" +
	"\x1bQueryDeviceByNoResponseData\x12H\n" +
	"\vdevice_info\x18\x01 \x01(\v2'.devicemanagementplatformapi.DeviceInfoR\n" +
	"deviceInfo\"\x9b\x01\n" +
	"\x17QueryDeviceByNoResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12L\n" +
	"\x04data\x18\x03 \x01(\v28.devicemanagementplatformapi.QueryDeviceByNoResponseDataR\x04data\"F\n" +
	"\x16QueryDeviceByIdRequest\x12,\n" +
	"\tdevice_id\x18\x01 \x01(\x03B\x0f\xe2\xdf\x1f\v\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\bdeviceId\"g\n" +
	"\x1bQueryDeviceByIdResponseData\x12H\n" +
	"\vdevice_info\x18\x01 \x01(\v2'.devicemanagementplatformapi.DeviceInfoR\n" +
	"deviceInfo\"\x9b\x01\n" +
	"\x17QueryDeviceByIdResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12L\n" +
	"\x04data\x18\x03 \x01(\v28.devicemanagementplatformapi.QueryDeviceByIdResponseDataR\x04data\">\n" +
	"\x15RegisterDeviceRequest\x12%\n" +
	"\tdevice_no\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p\x00xdR\bdeviceNo\"f\n" +
	"\x1aRegisterDeviceResponseData\x12H\n" +
	"\vdevice_info\x18\x01 \x01(\v2'.devicemanagementplatformapi.DeviceInfoR\n" +
	"deviceInfo\"\x99\x01\n" +
	"\x16RegisterDeviceResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12K\n" +
	"\x04data\x18\x03 \x01(\v27.devicemanagementplatformapi.RegisterDeviceResponseDataR\x04data2\xf5\x03\n" +
	"\x1bDeviceManagementPlatformAPI\x12\x9c\x01\n" +
	"\x0fQueryDeviceByNo\x123.devicemanagementplatformapi.QueryDeviceByNoRequest\x1a4.devicemanagementplatformapi.QueryDeviceByNoResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/devices/getDeviceByNo\x12\x9c\x01\n" +
	"\x0fQueryDeviceById\x123.devicemanagementplatformapi.QueryDeviceByIdRequest\x1a4.devicemanagementplatformapi.QueryDeviceByIdResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/devices/getDeviceById\x12\x97\x01\n" +
	"\x0eRegisterDevice\x122.devicemanagementplatformapi.RegisterDeviceRequest\x1a3.devicemanagementplatformapi.RegisterDeviceResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/devices/registerB Z\x1e./;devicemanagementplatformapib\x06proto3"

var (
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescOnce sync.Once
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescData []byte
)

func file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescGZIP() []byte {
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescOnce.Do(func() {
		file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc), len(file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc)))
	})
	return file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDescData
}

var file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_devicemanagementplatformapi_devicemanagementplatformapi_proto_goTypes = []any{
	(*DeviceInfo)(nil),                  // 0: devicemanagementplatformapi.DeviceInfo
	(*QueryDeviceByNoRequest)(nil),      // 1: devicemanagementplatformapi.QueryDeviceByNoRequest
	(*QueryDeviceByNoResponseData)(nil), // 2: devicemanagementplatformapi.QueryDeviceByNoResponseData
	(*QueryDeviceByNoResponse)(nil),     // 3: devicemanagementplatformapi.QueryDeviceByNoResponse
	(*QueryDeviceByIdRequest)(nil),      // 4: devicemanagementplatformapi.QueryDeviceByIdRequest
	(*QueryDeviceByIdResponseData)(nil), // 5: devicemanagementplatformapi.QueryDeviceByIdResponseData
	(*QueryDeviceByIdResponse)(nil),     // 6: devicemanagementplatformapi.QueryDeviceByIdResponse
	(*RegisterDeviceRequest)(nil),       // 7: devicemanagementplatformapi.RegisterDeviceRequest
	(*RegisterDeviceResponseData)(nil),  // 8: devicemanagementplatformapi.RegisterDeviceResponseData
	(*RegisterDeviceResponse)(nil),      // 9: devicemanagementplatformapi.RegisterDeviceResponse
}
var file_devicemanagementplatformapi_devicemanagementplatformapi_proto_depIdxs = []int32{
	0, // 0: devicemanagementplatformapi.QueryDeviceByNoResponseData.device_info:type_name -> devicemanagementplatformapi.DeviceInfo
	2, // 1: devicemanagementplatformapi.QueryDeviceByNoResponse.data:type_name -> devicemanagementplatformapi.QueryDeviceByNoResponseData
	0, // 2: devicemanagementplatformapi.QueryDeviceByIdResponseData.device_info:type_name -> devicemanagementplatformapi.DeviceInfo
	5, // 3: devicemanagementplatformapi.QueryDeviceByIdResponse.data:type_name -> devicemanagementplatformapi.QueryDeviceByIdResponseData
	0, // 4: devicemanagementplatformapi.RegisterDeviceResponseData.device_info:type_name -> devicemanagementplatformapi.DeviceInfo
	8, // 5: devicemanagementplatformapi.RegisterDeviceResponse.data:type_name -> devicemanagementplatformapi.RegisterDeviceResponseData
	1, // 6: devicemanagementplatformapi.DeviceManagementPlatformAPI.QueryDeviceByNo:input_type -> devicemanagementplatformapi.QueryDeviceByNoRequest
	4, // 7: devicemanagementplatformapi.DeviceManagementPlatformAPI.QueryDeviceById:input_type -> devicemanagementplatformapi.QueryDeviceByIdRequest
	7, // 8: devicemanagementplatformapi.DeviceManagementPlatformAPI.RegisterDevice:input_type -> devicemanagementplatformapi.RegisterDeviceRequest
	3, // 9: devicemanagementplatformapi.DeviceManagementPlatformAPI.QueryDeviceByNo:output_type -> devicemanagementplatformapi.QueryDeviceByNoResponse
	6, // 10: devicemanagementplatformapi.DeviceManagementPlatformAPI.QueryDeviceById:output_type -> devicemanagementplatformapi.QueryDeviceByIdResponse
	9, // 11: devicemanagementplatformapi.DeviceManagementPlatformAPI.RegisterDevice:output_type -> devicemanagementplatformapi.RegisterDeviceResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_devicemanagementplatformapi_devicemanagementplatformapi_proto_init() }
func file_devicemanagementplatformapi_devicemanagementplatformapi_proto_init() {
	if File_devicemanagementplatformapi_devicemanagementplatformapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc), len(file_devicemanagementplatformapi_devicemanagementplatformapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devicemanagementplatformapi_devicemanagementplatformapi_proto_goTypes,
		DependencyIndexes: file_devicemanagementplatformapi_devicemanagementplatformapi_proto_depIdxs,
		MessageInfos:      file_devicemanagementplatformapi_devicemanagementplatformapi_proto_msgTypes,
	}.Build()
	File_devicemanagementplatformapi_devicemanagementplatformapi_proto = out.File
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_goTypes = nil
	file_devicemanagementplatformapi_devicemanagementplatformapi_proto_depIdxs = nil
}
