// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kitkv/kitkv.proto

package kitkv

import (
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_kitkv_kitkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitkv_kitkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_kitkv_kitkv_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StoreResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponseData) Reset() {
	*x = StoreResponseData{}
	mi := &file_kitkv_kitkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponseData) ProtoMessage() {}

func (x *StoreResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_kitkv_kitkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponseData.ProtoReflect.Descriptor instead.
func (*StoreResponseData) Descriptor() ([]byte, []int) {
	return file_kitkv_kitkv_proto_rawDescGZIP(), []int{1}
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *StoreResponseData     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_kitkv_kitkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitkv_kitkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_kitkv_kitkv_proto_rawDescGZIP(), []int{2}
}

func (x *StoreResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *StoreResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *StoreResponse) GetData() *StoreResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_kitkv_kitkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitkv_kitkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_kitkv_kitkv_proto_rawDescGZIP(), []int{3}
}

func (x *LoadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LoadResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponseData) Reset() {
	*x = LoadResponseData{}
	mi := &file_kitkv_kitkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponseData) ProtoMessage() {}

func (x *LoadResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_kitkv_kitkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponseData.ProtoReflect.Descriptor instead.
func (*LoadResponseData) Descriptor() ([]byte, []int) {
	return file_kitkv_kitkv_proto_rawDescGZIP(), []int{4}
}

func (x *LoadResponseData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *LoadResponseData      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_kitkv_kitkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitkv_kitkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_kitkv_kitkv_proto_rawDescGZIP(), []int{5}
}

func (x *LoadResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *LoadResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *LoadResponse) GetData() *LoadResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_kitkv_kitkv_proto protoreflect.FileDescriptor

const file_kitkv_kitkv_proto_rawDesc = "" +
	"\n" +
	"\x11kitkv/kitkv.proto\x12\x05kitkv\x1a+mwitkow/go-proto-validators/validator.proto\x1a\x1cgoogle/api/annotations.proto\"K\n" +
	"\fStoreRequest\x12\x1a\n" +
	"\x03key\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x@R\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\fB\t\xe2\xdf\x1f\x05p\x00x\x80\x04R\x05value\"\x13\n" +
	"\x11StoreResponseData\"q\n" +
	"\rStoreResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12,\n" +
	"\x04data\x18\x03 \x01(\v2\x18.kitkv.StoreResponseDataR\x04data\")\n" +
	"\vLoadRequest\x12\x1a\n" +
	"\x03key\x18\x01 \x01(\tB\b\xe2\xdf\x1f\x04p\x00x@R\x03key\",\n" +
	"\x10LoadResponseData\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"o\n" +
	"\fLoadResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.kitkv.LoadResponseDataR\x04data2\xb8\x01\n" +
	"\x0fStoreServiceAPI\x12U\n" +
	"\x05Store\x12\x13.kitkv.StoreRequest\x1a\x14.kitkv.StoreResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/storeservice/store\x12N\n" +
	"\x04Load\x12\x12.kitkv.LoadRequest\x1a\x13.kitkv.LoadResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/storeservice/loadB)Z'github.com/KitHub/protocols/kitkv;kitkvb\x06proto3"

var (
	file_kitkv_kitkv_proto_rawDescOnce sync.Once
	file_kitkv_kitkv_proto_rawDescData []byte
)

func file_kitkv_kitkv_proto_rawDescGZIP() []byte {
	file_kitkv_kitkv_proto_rawDescOnce.Do(func() {
		file_kitkv_kitkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kitkv_kitkv_proto_rawDesc), len(file_kitkv_kitkv_proto_rawDesc)))
	})
	return file_kitkv_kitkv_proto_rawDescData
}

var file_kitkv_kitkv_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kitkv_kitkv_proto_goTypes = []any{
	(*StoreRequest)(nil),      // 0: kitkv.StoreRequest
	(*StoreResponseData)(nil), // 1: kitkv.StoreResponseData
	(*StoreResponse)(nil),     // 2: kitkv.StoreResponse
	(*LoadRequest)(nil),       // 3: kitkv.LoadRequest
	(*LoadResponseData)(nil),  // 4: kitkv.LoadResponseData
	(*LoadResponse)(nil),      // 5: kitkv.LoadResponse
}
var file_kitkv_kitkv_proto_depIdxs = []int32{
	1, // 0: kitkv.StoreResponse.data:type_name -> kitkv.StoreResponseData
	4, // 1: kitkv.LoadResponse.data:type_name -> kitkv.LoadResponseData
	0, // 2: kitkv.StoreServiceAPI.Store:input_type -> kitkv.StoreRequest
	3, // 3: kitkv.StoreServiceAPI.Load:input_type -> kitkv.LoadRequest
	2, // 4: kitkv.StoreServiceAPI.Store:output_type -> kitkv.StoreResponse
	5, // 5: kitkv.StoreServiceAPI.Load:output_type -> kitkv.LoadResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kitkv_kitkv_proto_init() }
func file_kitkv_kitkv_proto_init() {
	if File_kitkv_kitkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kitkv_kitkv_proto_rawDesc), len(file_kitkv_kitkv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kitkv_kitkv_proto_goTypes,
		DependencyIndexes: file_kitkv_kitkv_proto_depIdxs,
		MessageInfos:      file_kitkv_kitkv_proto_msgTypes,
	}.Build()
	File_kitkv_kitkv_proto = out.File
	file_kitkv_kitkv_proto_goTypes = nil
	file_kitkv_kitkv_proto_depIdxs = nil
}
