// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: kitkv/kitkv.proto

package kitkv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreServiceAPI_Store_FullMethodName = "/kitkv.StoreServiceAPI/Store"
	StoreServiceAPI_Load_FullMethodName  = "/kitkv.StoreServiceAPI/Load"
)

// StoreServiceAPIClient is the client API for StoreServiceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreServiceAPIClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
}

type storeServiceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceAPIClient(cc grpc.ClientConnInterface) StoreServiceAPIClient {
	return &storeServiceAPIClient{cc}
}

func (c *storeServiceAPIClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, StoreServiceAPI_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceAPIClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, StoreServiceAPI_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceAPIServer is the server API for StoreServiceAPI service.
// All implementations must embed UnimplementedStoreServiceAPIServer
// for forward compatibility.
type StoreServiceAPIServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Load(context.Context, *LoadRequest) (*LoadResponse, error)
	mustEmbedUnimplementedStoreServiceAPIServer()
}

// UnimplementedStoreServiceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceAPIServer struct{}

func (UnimplementedStoreServiceAPIServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedStoreServiceAPIServer) Load(context.Context, *LoadRequest) (*LoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedStoreServiceAPIServer) mustEmbedUnimplementedStoreServiceAPIServer() {}
func (UnimplementedStoreServiceAPIServer) testEmbeddedByValue()                         {}

// UnsafeStoreServiceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceAPIServer will
// result in compilation errors.
type UnsafeStoreServiceAPIServer interface {
	mustEmbedUnimplementedStoreServiceAPIServer()
}

func RegisterStoreServiceAPIServer(s grpc.ServiceRegistrar, srv StoreServiceAPIServer) {
	// If the following call panics, it indicates UnimplementedStoreServiceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreServiceAPI_ServiceDesc, srv)
}

func _StoreServiceAPI_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceAPIServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreServiceAPI_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceAPIServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreServiceAPI_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceAPIServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreServiceAPI_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceAPIServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreServiceAPI_ServiceDesc is the grpc.ServiceDesc for StoreServiceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreServiceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kitkv.StoreServiceAPI",
	HandlerType: (*StoreServiceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _StoreServiceAPI_Store_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _StoreServiceAPI_Load_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kitkv/kitkv.proto",
}
