// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/KitHub/protocols/compute_operation/compute_operation.proto

package compute_operation

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *LogicCompute) Validate() error {
	return nil
}
func (this *LogicCompute_LogicNode) Validate() error {
	for _, item := range this.Children {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Children", err)
			}
		}
	}
	return nil
}
func (this *LogicCompute_FieldConditionNode) Validate() error {
	return nil
}
func (this *LogicCompute_ConditionNode) Validate() error {
	if oneOfNester, ok := this.GetNode().(*LogicCompute_ConditionNode_LogicNode); ok {
		if oneOfNester.LogicNode != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.LogicNode); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("LogicNode", err)
			}
		}
	}
	if oneOfNester, ok := this.GetNode().(*LogicCompute_ConditionNode_ConditionNode); ok {
		if oneOfNester.ConditionNode != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.ConditionNode); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ConditionNode", err)
			}
		}
	}
	return nil
}
func (this *SetCompute) Validate() error {
	return nil
}
func (this *SetCompute_Node) Validate() error {
	for _, item := range this.Children {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Children", err)
			}
		}
	}
	return nil
}
