// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: kms_api/kms_api.proto

package kms_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KMSAPI_Store_FullMethodName = "/kms_api.KMSAPI/Store"
	KMSAPI_Load_FullMethodName  = "/kms_api.KMSAPI/Load"
)

// KMSAPIClient is the client API for KMSAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KMSAPIClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
}

type kMSAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewKMSAPIClient(cc grpc.ClientConnInterface) KMSAPIClient {
	return &kMSAPIClient{cc}
}

func (c *kMSAPIClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, KMSAPI_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSAPIClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, KMSAPI_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KMSAPIServer is the server API for KMSAPI service.
// All implementations must embed UnimplementedKMSAPIServer
// for forward compatibility.
type KMSAPIServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Load(context.Context, *LoadRequest) (*LoadResponse, error)
	mustEmbedUnimplementedKMSAPIServer()
}

// UnimplementedKMSAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKMSAPIServer struct{}

func (UnimplementedKMSAPIServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedKMSAPIServer) Load(context.Context, *LoadRequest) (*LoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedKMSAPIServer) mustEmbedUnimplementedKMSAPIServer() {}
func (UnimplementedKMSAPIServer) testEmbeddedByValue()                {}

// UnsafeKMSAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KMSAPIServer will
// result in compilation errors.
type UnsafeKMSAPIServer interface {
	mustEmbedUnimplementedKMSAPIServer()
}

func RegisterKMSAPIServer(s grpc.ServiceRegistrar, srv KMSAPIServer) {
	// If the following call panics, it indicates UnimplementedKMSAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KMSAPI_ServiceDesc, srv)
}

func _KMSAPI_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSAPIServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSAPI_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSAPIServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSAPI_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSAPIServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSAPI_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSAPIServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KMSAPI_ServiceDesc is the grpc.ServiceDesc for KMSAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KMSAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kms_api.KMSAPI",
	HandlerType: (*KMSAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _KMSAPI_Store_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _KMSAPI_Load_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kms_api/kms_api.proto",
}
