// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: compute_operation/compute_operation.proto

package compute_operation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 逻辑运算符枚举
type LogicOp int32

const (
	LogicOp_LOGIC_OP_UNSPECIFIED LogicOp = 0
	LogicOp_LOGIC_OP_AND         LogicOp = 1
	LogicOp_LOGIC_OP_OR          LogicOp = 2
)

// Enum value maps for LogicOp.
var (
	LogicOp_name = map[int32]string{
		0: "LOGIC_OP_UNSPECIFIED",
		1: "LOGIC_OP_AND",
		2: "LOGIC_OP_OR",
	}
	LogicOp_value = map[string]int32{
		"LOGIC_OP_UNSPECIFIED": 0,
		"LOGIC_OP_AND":         1,
		"LOGIC_OP_OR":          2,
	}
)

func (x LogicOp) Enum() *LogicOp {
	p := new(LogicOp)
	*p = x
	return p
}

func (x LogicOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicOp) Descriptor() protoreflect.EnumDescriptor {
	return file_compute_operation_compute_operation_proto_enumTypes[0].Descriptor()
}

func (LogicOp) Type() protoreflect.EnumType {
	return &file_compute_operation_compute_operation_proto_enumTypes[0]
}

func (x LogicOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicOp.Descriptor instead.
func (LogicOp) EnumDescriptor() ([]byte, []int) {
	return file_compute_operation_compute_operation_proto_rawDescGZIP(), []int{0}
}

// 比较运算符枚举
type CompareOp int32

const (
	CompareOp_COMPARE_OP_UNSPECIFIED CompareOp = 0  // unspecified
	CompareOp_COMPARE_OP_EQ          CompareOp = 1  // =
	CompareOp_COMPARE_OP_NEQ         CompareOp = 2  // !=
	CompareOp_COMPARE_OP_GT          CompareOp = 3  // >
	CompareOp_COMPARE_OP_GTE         CompareOp = 4  // >=
	CompareOp_COMPARE_OP_LT          CompareOp = 5  // <
	CompareOp_COMPARE_OP_LTE         CompareOp = 6  // <=
	CompareOp_COMPARE_OP_LIKE        CompareOp = 7  // like
	CompareOp_COMPARE_OP_NOT_LIKE    CompareOp = 8  // not like
	CompareOp_COMPARE_OP_IN          CompareOp = 9  // in
	CompareOp_COMPARE_OP_NOT_IN      CompareOp = 10 // not in
	CompareOp_COMPARE_OP_IS_NULL     CompareOp = 11 // is null
	CompareOp_COMPARE_OP_IS_NOT_NULL CompareOp = 12 // is not null
)

// Enum value maps for CompareOp.
var (
	CompareOp_name = map[int32]string{
		0:  "COMPARE_OP_UNSPECIFIED",
		1:  "COMPARE_OP_EQ",
		2:  "COMPARE_OP_NEQ",
		3:  "COMPARE_OP_GT",
		4:  "COMPARE_OP_GTE",
		5:  "COMPARE_OP_LT",
		6:  "COMPARE_OP_LTE",
		7:  "COMPARE_OP_LIKE",
		8:  "COMPARE_OP_NOT_LIKE",
		9:  "COMPARE_OP_IN",
		10: "COMPARE_OP_NOT_IN",
		11: "COMPARE_OP_IS_NULL",
		12: "COMPARE_OP_IS_NOT_NULL",
	}
	CompareOp_value = map[string]int32{
		"COMPARE_OP_UNSPECIFIED": 0,
		"COMPARE_OP_EQ":          1,
		"COMPARE_OP_NEQ":         2,
		"COMPARE_OP_GT":          3,
		"COMPARE_OP_GTE":         4,
		"COMPARE_OP_LT":          5,
		"COMPARE_OP_LTE":         6,
		"COMPARE_OP_LIKE":        7,
		"COMPARE_OP_NOT_LIKE":    8,
		"COMPARE_OP_IN":          9,
		"COMPARE_OP_NOT_IN":      10,
		"COMPARE_OP_IS_NULL":     11,
		"COMPARE_OP_IS_NOT_NULL": 12,
	}
)

func (x CompareOp) Enum() *CompareOp {
	p := new(CompareOp)
	*p = x
	return p
}

func (x CompareOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompareOp) Descriptor() protoreflect.EnumDescriptor {
	return file_compute_operation_compute_operation_proto_enumTypes[1].Descriptor()
}

func (CompareOp) Type() protoreflect.EnumType {
	return &file_compute_operation_compute_operation_proto_enumTypes[1]
}

func (x CompareOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompareOp.Descriptor instead.
func (CompareOp) EnumDescriptor() ([]byte, []int) {
	return file_compute_operation_compute_operation_proto_rawDescGZIP(), []int{1}
}

// 逻辑节点：AND/OR 分组节点
type LogicNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logic         LogicOp                `protobuf:"varint,1,opt,name=logic,proto3,enum=compute_operation.LogicOp" json:"logic,omitempty"`
	Children      []*ConditionNode       `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicNode) Reset() {
	*x = LogicNode{}
	mi := &file_compute_operation_compute_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicNode) ProtoMessage() {}

func (x *LogicNode) ProtoReflect() protoreflect.Message {
	mi := &file_compute_operation_compute_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicNode.ProtoReflect.Descriptor instead.
func (*LogicNode) Descriptor() ([]byte, []int) {
	return file_compute_operation_compute_operation_proto_rawDescGZIP(), []int{0}
}

func (x *LogicNode) GetLogic() LogicOp {
	if x != nil {
		return x.Logic
	}
	return LogicOp_LOGIC_OP_UNSPECIFIED
}

func (x *LogicNode) GetChildren() []*ConditionNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// 字段条件叶子节点
type FieldConditionNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      CompareOp              `protobuf:"varint,2,opt,name=operator,proto3,enum=compute_operation.CompareOp" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TableAlias    string                 `protobuf:"bytes,5,opt,name=table_alias,json=tableAlias,proto3" json:"table_alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldConditionNode) Reset() {
	*x = FieldConditionNode{}
	mi := &file_compute_operation_compute_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldConditionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConditionNode) ProtoMessage() {}

func (x *FieldConditionNode) ProtoReflect() protoreflect.Message {
	mi := &file_compute_operation_compute_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConditionNode.ProtoReflect.Descriptor instead.
func (*FieldConditionNode) Descriptor() ([]byte, []int) {
	return file_compute_operation_compute_operation_proto_rawDescGZIP(), []int{1}
}

func (x *FieldConditionNode) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldConditionNode) GetOperator() CompareOp {
	if x != nil {
		return x.Operator
	}
	return CompareOp_COMPARE_OP_UNSPECIFIED
}

func (x *FieldConditionNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FieldConditionNode) GetTableAlias() string {
	if x != nil {
		return x.TableAlias
	}
	return ""
}

// 条件节点总结构：oneof 实现两种节点互斥（替代Go接口多态）
type ConditionNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前节点是否取反 NOT
	Not bool `protobuf:"varint,1,opt,name=not,proto3" json:"not,omitempty"`
	// 二选一：要么是逻辑组，要么是单条件
	//
	// Types that are valid to be assigned to Node:
	//
	//	*ConditionNode_LogicNode
	//	*ConditionNode_ConditionNode
	Node          isConditionNode_Node `protobuf_oneof:"node"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionNode) Reset() {
	*x = ConditionNode{}
	mi := &file_compute_operation_compute_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionNode) ProtoMessage() {}

func (x *ConditionNode) ProtoReflect() protoreflect.Message {
	mi := &file_compute_operation_compute_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionNode.ProtoReflect.Descriptor instead.
func (*ConditionNode) Descriptor() ([]byte, []int) {
	return file_compute_operation_compute_operation_proto_rawDescGZIP(), []int{2}
}

func (x *ConditionNode) GetNot() bool {
	if x != nil {
		return x.Not
	}
	return false
}

func (x *ConditionNode) GetNode() isConditionNode_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ConditionNode) GetLogicNode() *LogicNode {
	if x != nil {
		if x, ok := x.Node.(*ConditionNode_LogicNode); ok {
			return x.LogicNode
		}
	}
	return nil
}

func (x *ConditionNode) GetConditionNode() *FieldConditionNode {
	if x != nil {
		if x, ok := x.Node.(*ConditionNode_ConditionNode); ok {
			return x.ConditionNode
		}
	}
	return nil
}

type isConditionNode_Node interface {
	isConditionNode_Node()
}

type ConditionNode_LogicNode struct {
	LogicNode *LogicNode `protobuf:"bytes,2,opt,name=logic_node,json=logicNode,proto3,oneof"`
}

type ConditionNode_ConditionNode struct {
	ConditionNode *FieldConditionNode `protobuf:"bytes,3,opt,name=condition_node,json=conditionNode,proto3,oneof"`
}

func (*ConditionNode_LogicNode) isConditionNode_Node() {}

func (*ConditionNode_ConditionNode) isConditionNode_Node() {}

var File_compute_operation_compute_operation_proto protoreflect.FileDescriptor

const file_compute_operation_compute_operation_proto_rawDesc = "" +
	"\n" +
	")compute_operation/compute_operation.proto\x12\x11compute_operation\"{\n" +
	"\tLogicNode\x120\n" +
	"\x05logic\x18\x01 \x01(\x0e2\x1a.compute_operation.LogicOpR\x05logic\x12<\n" +
	"\bchildren\x18\x02 \x03(\v2 .compute_operation.ConditionNodeR\bchildren\"\x9b\x01\n" +
	"\x12FieldConditionNode\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x128\n" +
	"\boperator\x18\x02 \x01(\x0e2\x1c.compute_operation.CompareOpR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1f\n" +
	"\vtable_alias\x18\x05 \x01(\tR\n" +
	"tableAlias\"\xb8\x01\n" +
	"\rConditionNode\x12\x10\n" +
	"\x03not\x18\x01 \x01(\bR\x03not\x12=\n" +
	"\n" +
	"logic_node\x18\x02 \x01(\v2\x1c.compute_operation.LogicNodeH\x00R\tlogicNode\x12N\n" +
	"\x0econdition_node\x18\x03 \x01(\v2%.compute_operation.FieldConditionNodeH\x00R\rconditionNodeB\x06\n" +
	"\x04node*F\n" +
	"\aLogicOp\x12\x18\n" +
	"\x14LOGIC_OP_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fLOGIC_OP_AND\x10\x01\x12\x0f\n" +
	"\vLOGIC_OP_OR\x10\x02*\xa8\x02\n" +
	"\tCompareOp\x12\x1a\n" +
	"\x16COMPARE_OP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCOMPARE_OP_EQ\x10\x01\x12\x12\n" +
	"\x0eCOMPARE_OP_NEQ\x10\x02\x12\x11\n" +
	"\rCOMPARE_OP_GT\x10\x03\x12\x12\n" +
	"\x0eCOMPARE_OP_GTE\x10\x04\x12\x11\n" +
	"\rCOMPARE_OP_LT\x10\x05\x12\x12\n" +
	"\x0eCOMPARE_OP_LTE\x10\x06\x12\x13\n" +
	"\x0fCOMPARE_OP_LIKE\x10\a\x12\x17\n" +
	"\x13COMPARE_OP_NOT_LIKE\x10\b\x12\x11\n" +
	"\rCOMPARE_OP_IN\x10\t\x12\x15\n" +
	"\x11COMPARE_OP_NOT_IN\x10\n" +
	"\x12\x16\n" +
	"\x12COMPARE_OP_IS_NULL\x10\v\x12\x1a\n" +
	"\x16COMPARE_OP_IS_NOT_NULL\x10\fB\x16Z\x14./;compute_operationb\x06proto3"

var (
	file_compute_operation_compute_operation_proto_rawDescOnce sync.Once
	file_compute_operation_compute_operation_proto_rawDescData []byte
)

func file_compute_operation_compute_operation_proto_rawDescGZIP() []byte {
	file_compute_operation_compute_operation_proto_rawDescOnce.Do(func() {
		file_compute_operation_compute_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compute_operation_compute_operation_proto_rawDesc), len(file_compute_operation_compute_operation_proto_rawDesc)))
	})
	return file_compute_operation_compute_operation_proto_rawDescData
}

var file_compute_operation_compute_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_compute_operation_compute_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_compute_operation_compute_operation_proto_goTypes = []any{
	(LogicOp)(0),               // 0: compute_operation.LogicOp
	(CompareOp)(0),             // 1: compute_operation.CompareOp
	(*LogicNode)(nil),          // 2: compute_operation.LogicNode
	(*FieldConditionNode)(nil), // 3: compute_operation.FieldConditionNode
	(*ConditionNode)(nil),      // 4: compute_operation.ConditionNode
}
var file_compute_operation_compute_operation_proto_depIdxs = []int32{
	0, // 0: compute_operation.LogicNode.logic:type_name -> compute_operation.LogicOp
	4, // 1: compute_operation.LogicNode.children:type_name -> compute_operation.ConditionNode
	1, // 2: compute_operation.FieldConditionNode.operator:type_name -> compute_operation.CompareOp
	2, // 3: compute_operation.ConditionNode.logic_node:type_name -> compute_operation.LogicNode
	3, // 4: compute_operation.ConditionNode.condition_node:type_name -> compute_operation.FieldConditionNode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_compute_operation_compute_operation_proto_init() }
func file_compute_operation_compute_operation_proto_init() {
	if File_compute_operation_compute_operation_proto != nil {
		return
	}
	file_compute_operation_compute_operation_proto_msgTypes[2].OneofWrappers = []any{
		(*ConditionNode_LogicNode)(nil),
		(*ConditionNode_ConditionNode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compute_operation_compute_operation_proto_rawDesc), len(file_compute_operation_compute_operation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_compute_operation_compute_operation_proto_goTypes,
		DependencyIndexes: file_compute_operation_compute_operation_proto_depIdxs,
		EnumInfos:         file_compute_operation_compute_operation_proto_enumTypes,
		MessageInfos:      file_compute_operation_compute_operation_proto_msgTypes,
	}.Build()
	File_compute_operation_compute_operation_proto = out.File
	file_compute_operation_compute_operation_proto_goTypes = nil
	file_compute_operation_compute_operation_proto_depIdxs = nil
}
