// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: kitdb/kitdb.proto

package kitdb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DemoAPI_Demo_FullMethodName = "/kitdb.DemoAPI/Demo"
)

// DemoAPIClient is the client API for DemoAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoAPIClient interface {
	Demo(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error)
}

type demoAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoAPIClient(cc grpc.ClientConnInterface) DemoAPIClient {
	return &demoAPIClient{cc}
}

func (c *demoAPIClient) Demo(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DemoResponse)
	err := c.cc.Invoke(ctx, DemoAPI_Demo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoAPIServer is the server API for DemoAPI service.
// All implementations must embed UnimplementedDemoAPIServer
// for forward compatibility.
type DemoAPIServer interface {
	Demo(context.Context, *DemoRequest) (*DemoResponse, error)
	mustEmbedUnimplementedDemoAPIServer()
}

// UnimplementedDemoAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemoAPIServer struct{}

func (UnimplementedDemoAPIServer) Demo(context.Context, *DemoRequest) (*DemoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Demo not implemented")
}
func (UnimplementedDemoAPIServer) mustEmbedUnimplementedDemoAPIServer() {}
func (UnimplementedDemoAPIServer) testEmbeddedByValue()                 {}

// UnsafeDemoAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoAPIServer will
// result in compilation errors.
type UnsafeDemoAPIServer interface {
	mustEmbedUnimplementedDemoAPIServer()
}

func RegisterDemoAPIServer(s grpc.ServiceRegistrar, srv DemoAPIServer) {
	// If the following call panics, it indicates UnimplementedDemoAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DemoAPI_ServiceDesc, srv)
}

func _DemoAPI_Demo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoAPIServer).Demo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemoAPI_Demo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoAPIServer).Demo(ctx, req.(*DemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DemoAPI_ServiceDesc is the grpc.ServiceDesc for DemoAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kitdb.DemoAPI",
	HandlerType: (*DemoAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Demo",
			Handler:    _DemoAPI_Demo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kitdb/kitdb.proto",
}
