// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kitdb/kitdb.proto

package kitdb

import (
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoRequest) Reset() {
	*x = DemoRequest{}
	mi := &file_kitdb_kitdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoRequest) ProtoMessage() {}

func (x *DemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitdb_kitdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoRequest.ProtoReflect.Descriptor instead.
func (*DemoRequest) Descriptor() ([]byte, []int) {
	return file_kitdb_kitdb_proto_rawDescGZIP(), []int{0}
}

type DemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoResponse) Reset() {
	*x = DemoResponse{}
	mi := &file_kitdb_kitdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoResponse) ProtoMessage() {}

func (x *DemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitdb_kitdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoResponse.ProtoReflect.Descriptor instead.
func (*DemoResponse) Descriptor() ([]byte, []int) {
	return file_kitdb_kitdb_proto_rawDescGZIP(), []int{1}
}

var File_kitdb_kitdb_proto protoreflect.FileDescriptor

const file_kitdb_kitdb_proto_rawDesc = "" +
	"\n" +
	"\x11kitdb/kitdb.proto\x12\x05kitdb\x1a+mwitkow/go-proto-validators/validator.proto\x1a\x1cgoogle/api/annotations.proto\"\r\n" +
	"\vDemoRequest\"\x0e\n" +
	"\fDemoResponse2O\n" +
	"\aDemoAPI\x12D\n" +
	"\x04Demo\x12\x12.kitdb.DemoRequest\x1a\x13.kitdb.DemoResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/demoB)Z'github.com/KitHub/protocols/kitdb;kitdbb\x06proto3"

var (
	file_kitdb_kitdb_proto_rawDescOnce sync.Once
	file_kitdb_kitdb_proto_rawDescData []byte
)

func file_kitdb_kitdb_proto_rawDescGZIP() []byte {
	file_kitdb_kitdb_proto_rawDescOnce.Do(func() {
		file_kitdb_kitdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kitdb_kitdb_proto_rawDesc), len(file_kitdb_kitdb_proto_rawDesc)))
	})
	return file_kitdb_kitdb_proto_rawDescData
}

var file_kitdb_kitdb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kitdb_kitdb_proto_goTypes = []any{
	(*DemoRequest)(nil),  // 0: kitdb.DemoRequest
	(*DemoResponse)(nil), // 1: kitdb.DemoResponse
}
var file_kitdb_kitdb_proto_depIdxs = []int32{
	0, // 0: kitdb.DemoAPI.Demo:input_type -> kitdb.DemoRequest
	1, // 1: kitdb.DemoAPI.Demo:output_type -> kitdb.DemoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kitdb_kitdb_proto_init() }
func file_kitdb_kitdb_proto_init() {
	if File_kitdb_kitdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kitdb_kitdb_proto_rawDesc), len(file_kitdb_kitdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kitdb_kitdb_proto_goTypes,
		DependencyIndexes: file_kitdb_kitdb_proto_depIdxs,
		MessageInfos:      file_kitdb_kitdb_proto_msgTypes,
	}.Build()
	File_kitdb_kitdb_proto = out.File
	file_kitdb_kitdb_proto_goTypes = nil
	file_kitdb_kitdb_proto_depIdxs = nil
}
