// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: TagMatchService/TagMatchService.proto

package TagMatchService

import (
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagMatchServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagMatchServiceRequest) Reset() {
	*x = TagMatchServiceRequest{}
	mi := &file_TagMatchService_TagMatchService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagMatchServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagMatchServiceRequest) ProtoMessage() {}

func (x *TagMatchServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TagMatchService_TagMatchService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagMatchServiceRequest.ProtoReflect.Descriptor instead.
func (*TagMatchServiceRequest) Descriptor() ([]byte, []int) {
	return file_TagMatchService_TagMatchService_proto_rawDescGZIP(), []int{0}
}

type TagMatchServiceResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagMatchServiceResponseData) Reset() {
	*x = TagMatchServiceResponseData{}
	mi := &file_TagMatchService_TagMatchService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagMatchServiceResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagMatchServiceResponseData) ProtoMessage() {}

func (x *TagMatchServiceResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_TagMatchService_TagMatchService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagMatchServiceResponseData.ProtoReflect.Descriptor instead.
func (*TagMatchServiceResponseData) Descriptor() ([]byte, []int) {
	return file_TagMatchService_TagMatchService_proto_rawDescGZIP(), []int{1}
}

type TagMatchServiceResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	ErrCode       int32                        `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg        string                       `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Data          *TagMatchServiceResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagMatchServiceResponse) Reset() {
	*x = TagMatchServiceResponse{}
	mi := &file_TagMatchService_TagMatchService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagMatchServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagMatchServiceResponse) ProtoMessage() {}

func (x *TagMatchServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TagMatchService_TagMatchService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagMatchServiceResponse.ProtoReflect.Descriptor instead.
func (*TagMatchServiceResponse) Descriptor() ([]byte, []int) {
	return file_TagMatchService_TagMatchService_proto_rawDescGZIP(), []int{2}
}

func (x *TagMatchServiceResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *TagMatchServiceResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *TagMatchServiceResponse) GetData() *TagMatchServiceResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_TagMatchService_TagMatchService_proto protoreflect.FileDescriptor

const file_TagMatchService_TagMatchService_proto_rawDesc = "" +
	"\n" +
	"%TagMatchService/TagMatchService.proto\x12\x0fTagMatchService\x1a+mwitkow/go-proto-validators/validator.proto\x1a\x1cgoogle/api/annotations.proto\"\x18\n" +
	"\x16TagMatchServiceRequest\"\x1d\n" +
	"\x1bTagMatchServiceResponseData\"\x8f\x01\n" +
	"\x17TagMatchServiceResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12@\n" +
	"\x04data\x18\x03 \x01(\v2,.TagMatchService.TagMatchServiceResponseDataR\x04data2\x98\x01\n" +
	"\x12TagMatchServiceAPI\x12\x81\x01\n" +
	"\x05Match\x12'.TagMatchService.TagMatchServiceRequest\x1a(.TagMatchService.TagMatchServiceResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/tagmatch/conditions/matchB=Z;github.com/KitHub/protocols/TagMatchService;TagMatchServiceb\x06proto3"

var (
	file_TagMatchService_TagMatchService_proto_rawDescOnce sync.Once
	file_TagMatchService_TagMatchService_proto_rawDescData []byte
)

func file_TagMatchService_TagMatchService_proto_rawDescGZIP() []byte {
	file_TagMatchService_TagMatchService_proto_rawDescOnce.Do(func() {
		file_TagMatchService_TagMatchService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TagMatchService_TagMatchService_proto_rawDesc), len(file_TagMatchService_TagMatchService_proto_rawDesc)))
	})
	return file_TagMatchService_TagMatchService_proto_rawDescData
}

var file_TagMatchService_TagMatchService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_TagMatchService_TagMatchService_proto_goTypes = []any{
	(*TagMatchServiceRequest)(nil),      // 0: TagMatchService.TagMatchServiceRequest
	(*TagMatchServiceResponseData)(nil), // 1: TagMatchService.TagMatchServiceResponseData
	(*TagMatchServiceResponse)(nil),     // 2: TagMatchService.TagMatchServiceResponse
}
var file_TagMatchService_TagMatchService_proto_depIdxs = []int32{
	1, // 0: TagMatchService.TagMatchServiceResponse.data:type_name -> TagMatchService.TagMatchServiceResponseData
	0, // 1: TagMatchService.TagMatchServiceAPI.Match:input_type -> TagMatchService.TagMatchServiceRequest
	2, // 2: TagMatchService.TagMatchServiceAPI.Match:output_type -> TagMatchService.TagMatchServiceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_TagMatchService_TagMatchService_proto_init() }
func file_TagMatchService_TagMatchService_proto_init() {
	if File_TagMatchService_TagMatchService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TagMatchService_TagMatchService_proto_rawDesc), len(file_TagMatchService_TagMatchService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TagMatchService_TagMatchService_proto_goTypes,
		DependencyIndexes: file_TagMatchService_TagMatchService_proto_depIdxs,
		MessageInfos:      file_TagMatchService_TagMatchService_proto_msgTypes,
	}.Build()
	File_TagMatchService_TagMatchService_proto = out.File
	file_TagMatchService_TagMatchService_proto_goTypes = nil
	file_TagMatchService_TagMatchService_proto_depIdxs = nil
}
