// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: TagMatchService/TagMatchService.proto

package TagMatchService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TagMatchServiceAPI_Match_FullMethodName = "/TagMatchService.TagMatchServiceAPI/Match"
)

// TagMatchServiceAPIClient is the client API for TagMatchServiceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TagMatchServiceAPIClient interface {
	Match(ctx context.Context, in *TagMatchServiceRequest, opts ...grpc.CallOption) (*TagMatchServiceResponse, error)
}

type tagMatchServiceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewTagMatchServiceAPIClient(cc grpc.ClientConnInterface) TagMatchServiceAPIClient {
	return &tagMatchServiceAPIClient{cc}
}

func (c *tagMatchServiceAPIClient) Match(ctx context.Context, in *TagMatchServiceRequest, opts ...grpc.CallOption) (*TagMatchServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagMatchServiceResponse)
	err := c.cc.Invoke(ctx, TagMatchServiceAPI_Match_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagMatchServiceAPIServer is the server API for TagMatchServiceAPI service.
// All implementations must embed UnimplementedTagMatchServiceAPIServer
// for forward compatibility.
type TagMatchServiceAPIServer interface {
	Match(context.Context, *TagMatchServiceRequest) (*TagMatchServiceResponse, error)
	mustEmbedUnimplementedTagMatchServiceAPIServer()
}

// UnimplementedTagMatchServiceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTagMatchServiceAPIServer struct{}

func (UnimplementedTagMatchServiceAPIServer) Match(context.Context, *TagMatchServiceRequest) (*TagMatchServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Match not implemented")
}
func (UnimplementedTagMatchServiceAPIServer) mustEmbedUnimplementedTagMatchServiceAPIServer() {}
func (UnimplementedTagMatchServiceAPIServer) testEmbeddedByValue()                            {}

// UnsafeTagMatchServiceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagMatchServiceAPIServer will
// result in compilation errors.
type UnsafeTagMatchServiceAPIServer interface {
	mustEmbedUnimplementedTagMatchServiceAPIServer()
}

func RegisterTagMatchServiceAPIServer(s grpc.ServiceRegistrar, srv TagMatchServiceAPIServer) {
	// If the following call panics, it indicates UnimplementedTagMatchServiceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TagMatchServiceAPI_ServiceDesc, srv)
}

func _TagMatchServiceAPI_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagMatchServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagMatchServiceAPIServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagMatchServiceAPI_Match_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagMatchServiceAPIServer).Match(ctx, req.(*TagMatchServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TagMatchServiceAPI_ServiceDesc is the grpc.ServiceDesc for TagMatchServiceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TagMatchServiceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TagMatchService.TagMatchServiceAPI",
	HandlerType: (*TagMatchServiceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Match",
			Handler:    _TagMatchServiceAPI_Match_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TagMatchService/TagMatchService.proto",
}
