// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: TagMatchService/TagMatchService.proto

package TagMatchService

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AddEntitesRequestEntityTuple) Validate() error {
	if !(len(this.EntityId) > 1) {
		return github_com_mwitkow_go_proto_validators.FieldError("EntityId", fmt.Errorf(`value '%v' must have a length greater than '1'`, this.EntityId))
	}
	if !(len(this.EntityId) < 64) {
		return github_com_mwitkow_go_proto_validators.FieldError("EntityId", fmt.Errorf(`value '%v' must have a length smaller than '64'`, this.EntityId))
	}
	if len(this.Tags) < 1 {
		return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must contain at least 1 elements`, this.Tags))
	}
	if len(this.Tags) > 10 {
		return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must contain at most 10 elements`, this.Tags))
	}
	for _, item := range this.Tags {
		if !(len(item) > 1) {
			return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must have a length greater than '1'`, item))
		}
		if !(len(item) < 64) {
			return github_com_mwitkow_go_proto_validators.FieldError("Tags", fmt.Errorf(`value '%v' must have a length smaller than '64'`, item))
		}
	}
	return nil
}
func (this *AddEntitiesRequest) Validate() error {
	if !(this.ProjectId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("ProjectId", fmt.Errorf(`value '%v' must be greater than '0'`, this.ProjectId))
	}
	if !(this.DataVersion > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("DataVersion", fmt.Errorf(`value '%v' must be greater than '0'`, this.DataVersion))
	}
	if len(this.Data) < 1 {
		return github_com_mwitkow_go_proto_validators.FieldError("Data", fmt.Errorf(`value '%v' must contain at least 1 elements`, this.Data))
	}
	if len(this.Data) > 50 {
		return github_com_mwitkow_go_proto_validators.FieldError("Data", fmt.Errorf(`value '%v' must contain at most 50 elements`, this.Data))
	}
	for _, item := range this.Data {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
			}
		}
	}
	return nil
}
func (this *AddEntitiesResponseData) Validate() error {
	return nil
}
func (this *AddEntitiesResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *MatchEntitesRequestCondition) Validate() error {
	if !(len(this.Tag) > 1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Tag", fmt.Errorf(`value '%v' must have a length greater than '1'`, this.Tag))
	}
	if !(len(this.Tag) < 64) {
		return github_com_mwitkow_go_proto_validators.FieldError("Tag", fmt.Errorf(`value '%v' must have a length smaller than '64'`, this.Tag))
	}
	if !(len(this.Value) > 1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Value", fmt.Errorf(`value '%v' must have a length greater than '1'`, this.Value))
	}
	if !(len(this.Value) < 64) {
		return github_com_mwitkow_go_proto_validators.FieldError("Value", fmt.Errorf(`value '%v' must have a length smaller than '64'`, this.Value))
	}
	return nil
}
func (this *MatchEntitesRequest) Validate() error {
	for _, item := range this.Conditions {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Conditions", err)
			}
		}
	}
	return nil
}
func (this *MatchEntitesResponseData) Validate() error {
	return nil
}
func (this *MatchEntitesResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
